//~ xml2abc-js, Revision: 122, Copyright (C) 2014-2025: Willem Vree
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ Lesser GNU General Public License as published by the Free Software Foundation;
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the Lesser GNU General Public License for more details. <http://www.gnu.org/licenses/lgpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var k=0;return function(){return k<d.length?{done:!1,value:d[k++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var k="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return k?k.call(d):$jscomp.arrayIterator(d)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,k,m){d!=Array.prototype&&d!=Object.prototype&&(d[k]=m.value)};$jscomp.getGlobal=function(d){d=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,d];for(var k=0;k<d.length;++k){var m=d[k];if(m&&m.Math==Math)return m}return globalThis};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(d,k,m,l){if(k){m=$jscomp.global;d=d.split(".");for(l=0;l<d.length-1;l++){var r=d[l];r in m||(m[r]={});m=m[r]}d=d[d.length-1];l=m[d];k=k(l);k!=l&&null!=k&&$jscomp.defineProperty(m,d,{configurable:!0,writable:!0,value:k})}};$jscomp.polyfill("Array.prototype.fill",function(d){return d?d:function(d,m,l){var k=this.length||0;0>m&&(m=Math.max(0,k+m));if(null==l||l>k)l=k;l=Number(l);0>l&&(l=Math.max(0,k+l));for(m=Number(m||0);m<l;m++)this[m]=d;return this}},"es6","es3");
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(d,k){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:k})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function d(m){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(m||"")+"_"+k++,m)}var k=0;return d}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.asyncIterator;d||(d=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};
$jscomp.iteratorFromArray=function(d,k){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var m=0,l={next:function(){if(m<d.length){var r=m++;return{value:k(r,d[r]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var d={},k=Object.create(new $jscomp.global.Proxy(d,{get:function(m,l,r){return m==d&&"q"==l&&r==k}}));return!0===k.q}catch(m){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(d,k){return Object.prototype.hasOwnProperty.call(d,k)};
$jscomp.polyfill("WeakMap",function(d){function k(){if(!d||!Object.seal)return!1;try{var E=Object.seal({}),l=Object.seal({}),y=new d([[E,2],[l,3]]);if(2!=y.get(E)||3!=y.get(l))return!1;y.delete(E);y.set(l,4);return!y.has(E)&&4==y.get(l)}catch(x){return!1}}function m(){}function l(d){var l=typeof d;return"object"===l&&null!==d||"function"===l}function r(d){if(!$jscomp.owns(d,A)){var l=new m;$jscomp.defineProperty(d,A,{value:l})}}function v(d){var l=Object[d];l&&(Object[d]=function(d){if(d instanceof
m)return d;r(d);return l(d)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(d&&$jscomp.ES6_CONFORMANCE)return d}else if(k())return d;var A="$jscomp_hidden_"+Math.random();v("freeze");v("preventExtensions");v("seal");var H=0,y=function(d){this.id_=(H+=Math.random()+1).toString();if(d){d=$jscomp.makeIterator(d);for(var l;!(l=d.next()).done;)l=l.value,this.set(l[0],l[1])}};y.prototype.set=function(d,y){if(!l(d))throw Error("Invalid WeakMap key");r(d);if(!$jscomp.owns(d,A))throw Error("WeakMap key fail: "+
d);d[A][this.id_]=y;return this};y.prototype.get=function(d){return l(d)&&$jscomp.owns(d,A)?d[A][this.id_]:void 0};y.prototype.has=function(d){return l(d)&&$jscomp.owns(d,A)&&$jscomp.owns(d[A],this.id_)};y.prototype.delete=function(d){return l(d)&&$jscomp.owns(d,A)&&$jscomp.owns(d[A],this.id_)?delete d[A][this.id_]:!1};return y},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(d){function k(){if($jscomp.ASSUME_NO_NATIVE_MAP||!d||"function"!=typeof d||!d.prototype.entries||"function"!=typeof Object.seal)return!1;try{var l=Object.seal({x:4}),m=new d($jscomp.makeIterator([[l,"s"]]));if("s"!=m.get(l)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var k=m.entries(),r=k.next();if(r.done||r.value[0]!=l||"s"!=r.value[1])return!1;r=k.next();return r.done||4!=r.value[0].x||"t"!=r.value[1]||!k.next().done?!1:!0}catch(x){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(d&&$jscomp.ES6_CONFORMANCE)return d}else if(k())return d;$jscomp.initSymbolIterator();var m=new WeakMap,l=function(d){this.data_={};this.head_=A();this.size=0;if(d){d=$jscomp.makeIterator(d);for(var l;!(l=d.next()).done;)l=l.value,this.set(l[0],l[1])}};l.prototype.set=function(d,l){d=0===d?0:d;var m=r(this,d);m.list||(m.list=this.data_[m.id]=[]);m.entry?m.entry.value=l:(m.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:d,
value:l},m.list.push(m.entry),this.head_.previous.next=m.entry,this.head_.previous=m.entry,this.size++);return this};l.prototype.delete=function(d){d=r(this,d);return d.entry&&d.list?(d.list.splice(d.index,1),d.list.length||delete this.data_[d.id],d.entry.previous.next=d.entry.next,d.entry.next.previous=d.entry.previous,d.entry.head=null,this.size--,!0):!1};l.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=A();this.size=0};l.prototype.has=function(d){return!!r(this,d).entry};
l.prototype.get=function(d){return(d=r(this,d).entry)&&d.value};l.prototype.entries=function(){return v(this,function(d){return[d.key,d.value]})};l.prototype.keys=function(){return v(this,function(d){return d.key})};l.prototype.values=function(){return v(this,function(d){return d.value})};l.prototype.forEach=function(d,l){for(var m=this.entries(),k;!(k=m.next()).done;)k=k.value,d.call(l,k[1],k[0],this)};l.prototype[Symbol.iterator]=l.prototype.entries;var r=function(d,l){var k=l&&typeof l;"object"==
k||"function"==k?m.has(l)?k=m.get(l):(k=""+ ++H,m.set(l,k)):k="p_"+l;var r=d.data_[k];if(r&&$jscomp.owns(d.data_,k))for(d=0;d<r.length;d++){var y=r[d];if(l!==l&&y.key!==y.key||l===y.key)return{id:k,list:r,index:d,entry:y}}return{id:k,list:r,index:-1,entry:void 0}},v=function(d,l){var m=d.head_;return $jscomp.iteratorPrototype(function(){if(m){for(;m.head!=d.head_;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},A=function(){var d={};return d.previous=
d.next=d.head=d},H=0;return l},"es6","es3");$jscomp.findInternal=function(d,k,m){d instanceof String&&(d=String(d));for(var l=d.length,r=0;r<l;r++){var v=d[r];if(k.call(m,v,r,d))return{i:r,v:v}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,m){return $jscomp.findInternal(this,d,m).v}},"es6","es3");$jscomp.polyfill("Object.entries",function(d){return d?d:function(d){var m=[],l;for(l in d)$jscomp.owns(d,l)&&m.push([l,d[l]]);return m}},"es8","es3");
var xml2abc_VERSION=122,vertaal;
(function(){function d(a,b){return Array(a+1).join(b)}function k(a,b){for(var c=0,h={};c<a.length;++c)h[a[c]]=b[c];return h}function m(a,b){var c=a.split(/%[ds]/);c.length>b.length&&b.push("");return b.map(function(a,b){return c[b]+a}).join("")}function l(a,b){u.info(m(a,b))}function r(a,b){return-1!==a.indexOf(b,a.length-b.length)}function v(a){return Object.keys(a).map(function(a){return parseInt(a)})}function A(a){return{"double-flat":"flat-flat","double-sharp":"sharp-sharp"}[a]||a}function H(a,
b){var c=[],h;if(Array.isArray(a))for(h=0;h<a.length;++h)h in a&&c.push([h,a[h]]);else for(h in a)c.push([h,a[h]]);c.sort(b?function(a,b){return a[0]-b[0]}:function(a,b){return a[1]-b[1]||b[0]-a[0]});return c}function y(a,b,c){this.ixp=a;this.ixm=b;this.mdur=c.mdur?c.mdur:0;this.divs=c.divs?c.divs:1;this.mtr=c.mtr?c.mtr:[4,4];this.lline=this.attr="";this.rline="|";this.lnum=""}function E(a,b){this.tijd=0;this.dur=a;this.type="";this.fact=null;this.tup=[""];this.tupabc="";this.grace=this.beam=0;this.before=
[];this.after="";this.ns=b?[b]:[];this.lyrs={};this.pos=0;this.tab=null;this.ntdec="";this.xmlvce=this.xmlstf=1}function F(a,b){this.tijd=0;this.str=a;this.pos=0;this.xmlstf=b;this.isbar=this.chsym=0}function I(){}function x(a){this.maxtime=this.tijd=0;this.gMaten=[];this.gLyrics=[];this.gChSyms=[];this.vnums={};this.wev=a.wev;this.cnt=new I;this.vceCnt=1;this.lastnote=null;this.bpl=a.b;this.cpl=a.n;this.rbm=a.rbm;this.repbra=0;this.nvlt=a.v;this.nbr=a.nbr}function J(a,b,c,h){this.fnmext=a;this.outlist=
[];this.infolist=[];this.title="T:Title";this.key="none";this.clefs=new Map;this.mtr="none";this.tempo=0;this.tempo_units=[1,4];this.pad=b;this.X=c+1;this.denL=h.d;this.volpan=h.m;this.cmpL=[];this.scale="";this.tstep=h.t;this.stemless=0;this.rightmargin=this.leftmargin=this.pagewidth="";this.shiftStem=h.s;this.mnum=h.mnum;4==h.p.length&&(this.scale=""!=h.p[0]?parseFloat(h.p[0]):"",this.pagewidth=""!=h.p[1]?parseFloat(h.p[1]):"",this.leftmargin=""!=h.p[2]?parseFloat(h.p[2]):"",this.rightmargin=""!=
h.p[3]?parseFloat(h.p[3]):"")}function X(a,b){if(!a.join(""))return["",0];for(var c=[],h=0;h<a.length;++h){var g=a[h];""==g?g=b?"_":"*":r(g,"_")&&!r(g,"\\_")?(g=g.replace("_",""),b=1):b=0;c.push(g)}return[c.join(" "),b]}function K(a,b){for(var c=a,h=b,g;b;)g=a%b,a=b,b=g;return[c/a,h/a]}function L(a,b,c){if(0==a.dur&&!a.grace)return"";var h=$jscomp.makeIterator(K(c*a.dur,4*b));b=h.next().value;h=h.next().value;a.grace&&(h=$jscomp.makeIterator(K(16,a.type||c)),b=h.next().value,h=h.next().value);a.fact&&
(c=$jscomp.makeIterator(a.fact),a=c.next().value,c=c.next().value,h=$jscomp.makeIterator(K(b*a,h*c)),b=h.next().value,h=h.next().value);64<h&&(a=b/h,c=Math.floor(a),a-c<.1*a&&(b=c,h=1),h=K(Math.round(64*b/h)||1,64),b=h[0],h=h[1]);return 1==b?1==h?"":2==h?"/":"/"+h:1==h?""+b:b+"/"+h}function P(a){var b=a.match(/([_^]*)([A-Ga-g])([',]*)/);if(!b)return-1;a=b[1];var c=b[2];b=b[3];var h=c.toUpperCase();c=60+[0,2,4,5,7,9,11]["CDEFGAB".indexOf(h)]+(h!=c?12:0);a&&(c+=("^"==a[0]?1:-1)*a.length);b&&(c+=("'"==
b[0]?12:-12)*b.length);return c}function Y(a,b,c,h){var g=0;0<=c.indexOf("stafflines=1")&&(g+=4);!h&&0<=c.indexOf("bass")&&(g+=12);g&&(c="CDEFGAB".split(""),g=c.indexOf(a)+g,a=c[g%7],b+=Math.floor(g/7));4<b&&(a=a.toLowerCase());5<b&&(a+=d(b-5,"'"));4>b&&(a+=d(4-b,","));return a}function Z(a,b,c){c={maj:8,ion:8,m:11,min:11,aeo:11,mix:9,dor:10,phr:12,lyd:7,loc:13,non:8};b=b.slice(0,3).toLowerCase();b="Fb Cb Gb Db Ab Eb Bb F C G D A E B F# C# G# D# A# E# B#".split(" ")[c[b]+a]+(8!=c[b]?b:"");c="FCGDAEB".split("");
a=0<=a?k(c.slice(0,a),Array(a).fill("sharp")):k(c.slice(a),Array(-a).fill("flat"));return[b,a]}function aa(a,b){var c="",h={},g="C exp ";a.find("key").children().each(function(){var a=$(this);"key-step"==a[0].tagName?(c&&(g+=" "+c),c=a.text().trim()):"key-alter"==a[0].tagName?(a=a.text().trim())&&(h[c]=Math.round(a)):"key-accidental"==a[0].tagName&&(a=A(a.text().trim()),h[c]=a,c=b.acc2abc(a)+c)});c&&(g+=" "+c);return[g,h]}function Q(a,b,c){var h=0,g=b[a];var e=g.tup.indexOf("start");-1<e&&g.tup.splice(e,
1);var f=a;for(c=[g.fact[0]/c[0],g.fact[1]/c[1]];a<b.length;){g=b[a];if(!(g instanceof F||g.grace)){-1<g.tup.indexOf("start")?(e=Q(a,b,c),a=e[0],e=e[1],h+=e):g.fact&&(h+=1);e=g.tup.indexOf("stop");if(-1<e){g.tup.splice(e,1);break}if(!g.fact){a=t;break}var t=a}a+=1}t=[c[0],c[1],h];t="3,2,3"==t.toString()?"(3":m("(%d:%d:%d",t);b[f].tupabc=t+b[f].tupabc;return[a,h]}function ba(a){a=a.filter(function(a){return a instanceof E});for(var b=0;b<a.length-1;){var c=a[b],h=a[b+1];!c.fact&&!h.fact&&0<c.dur&&
h.beam&&(3*c.dur==h.dur?(h.dur=2*h.dur/3,c.dur*=2,c.after="<"+c.after,b+=1):3*h.dur==c.dur&&(c.dur=2*c.dur/3,h.dur*=2,c.after=">"+c.after,b+=1));b+=1}}function ca(a,b,c){var h=b;8==c[1]&&(h=b/2);a=Math.floor(a.tijd/h);8==c[1]&&(a=7==c[0]||5==c[0]?[0,0,0,1,1,2,2][a]:Math.floor(a/3));return[a,h]}function da(a,b,c,h,g,e){for(var f=0,t;f<a.length;)t=a[f],t instanceof E&&t.fact&&!t.grace&&(t=Q(f,a,[1,1]),f=t[0]),f+=1;f=[];for(var d,p,G=-1,l=0,q=0;q<a.length;++q){t=a[q];if(t instanceof E){d=L(t,c,h);var m=
1<t.ns.length;p=t.ns.filter(function(a){return r(a,"-")});p=p.map(function(a){return a.slice(0,-1)});var k="";m&&p.length==t.ns.length&&(t.ns=p,k="-");p=t.tupabc+t.before.join("");m&&(p+="[");p+=t.ns.join("");m&&(p+="]"+k);r(p,"-")&&(p=p.slice(0,-1),k="-");p+=d+k;p+=t.after;d=t.beam;k=$jscomp.makeIterator(ca(t,c,e));m=k.next().value;k=k.next().value;g&&t.dur<c&&l<c&&((d=m==G)||0==t.tijd%k||(d=!0));G=m;l=t.dur}else{if(t.isbar){p=[];d=0;m=$jscomp.makeIterator(b);for(k=m.next();!k.done;k=m.next()){var D=
k.value;D.dur=D.tijd-d;D.grace=0;D.fact=0;0==D.dur?p.push(D.str):(d=L(D,c,h),p.push("x"+d+D.str));d=D.tijd}p.length&&(D.dur=t.tijd-d,d=L(D,c,h),f=f.concat(["&"],p,["x"+d]))}else t.str instanceof Array&&(t.str=t.str[0]);p=t.str;d=1}d?f.push(p):f.push(" "+p)}for(f=f.join("");0<=f.indexOf("!ped!!ped!");)f=f.replace(/!ped!!ped!/g,"!ped!");for(;0<=f.indexOf("!ped-up!!ped-up!");)f=f.replace(/!ped-up!!ped-up!/g,"!ped-up!");for(;0<=f.indexOf("!8va(!!8va)!");)f=f.replace(/!8va\(!!8va\)!/g,"");return f}function R(a,
b,c,h,g,e){var f=b[c];a.xmlstf&&0<a.xmlstf&&a.xmlstf!=f?(h=[g.length,f],f=a.xmlstf-f,b[c]=a.xmlstf,b=new F("[I:staff "+(0<f?"+":"")+f+"]"),b.tijd=e,g.push(b)):h=[];g.push(a);return h}function ea(a,b,c,h,g){a.map(function(a,b){a.pos=b});a.sort(function(a,b){return a.tijd-b.tijd||a.pos-b.pos});for(var e=0,f=[],t=[],d=[],p=0,G=[],m=0;m<a.length;++m){var q=a[m];q.tijd>e&&N(q.tijd-e,b)&&(f.push(new E(q.tijd-e,"x")),d.push(f.length-1));if(q instanceof F)q.chsym&&q.offset?(q.tijd+=Math.floor(q.offset),t.push(q)):
q.chsym&&q.tijd<e?t.push(q):(q.tijd<e&&(q.tijd=e),R(q,c,g,G,f,e),e=q.tijd);else{g=h?q.xmlvce+100*q.xmlstf:q.xmlvce;if(q.tijd<e){if("z"==q.ns[0])continue;var k=f[p];if(k.tijd<=q.tijd)if("z"==k.ns[0]){k.dur=q.tijd-k.tijd;if(0==k.dur&&(f.splice(p,1),G.length)){var r=$jscomp.makeIterator(G);k=r.next().value;r=r.next().value;f.splice(k,1);c[g]=r}l("overlap in part %d, measure %d: rest shortened",[b.ixp+1,b.ixm+1])}else{k.ns=k.ns.concat(q.ns);l("overlap in part %d, measure %d: added chord",[b.ixp+1,b.ixm+
1]);q.dur=q.tijd+q.dur-e;if(0>=q.dur)continue;q.tijd=e}else{l("overlapping notes in one voice! part %d, measure %d, note %s discarded",[b.ixp+1,b.ixm+1,q instanceof E?q.ns:q.str]);continue}}G=R(q,c,g,G,f,e);if(q instanceof E)if(p=f.length-1,e=q.ns[0],"x"==e||"z"==e)d.push(f.length-1);else if(d.length){if(q.beam&&!q.grace)for(e=0;e<d.length;++e)f[d[e]].beam=q.beam;d=[]}e=q.tijd+q.dur}}0==e&&(l("empty measure in part %d, measure %d, it should contain at least a rest to advance the time!",[b.ixp+1,b.ixm+
1]),e=new E(b.mdur,"z"),a=f[f.length-1],a.str&&a.str.match(/[|:\]]/)&&(a.tijd=b.mdur,f=f.slice(0,-1).concat([e,a])));return[f,t]}function fa(a){function b(a){var b=$("<part-group></part-group>",h);b.attr("number",a);b.attr("type","stop");return b}var c,h=a[0];var g=[];var e=[];var f=a.children();for(c=0;c<f.length;c++)if(a=$(f[c]),"part-group"==a[0].tagName){var d=a.attr("number");var n=a.attr("type");var p=e.indexOf(d);"start"==n?-1<p?(g.push(b(d)),g.push(a)):(g.push(a),e.push(d)):-1<p&&(e.splice(p,
1),g.push(a))}else g.push(a);for(c=e.length-1;0<=c;--c)d=e[c],g.push(b(d));return g}function M(a,b,c){if(0==a.length)return[[],[]];var h=a.shift();if("part-group"==h[0].tagName){var g=h.attr("number");var e=h.attr("type");if("start"==e){e=[];for(f in{"group-symbol":0,"group-barline":0,"group-name":0,"group-abbreviation":0})e.push(h.find(f).text()||"");b[g]=e;c.push(g);var f=M(a,b,c);a=f[0];h=f[1];f=M(h,b,c);b=f[0];c=f[1];return[[a].concat(b),c]}c=c.pop();a.length&&"stop"==a[0].attr("type")&&g!=c&&
(f=b[c],b[c]=b[g],b[g]=f);b=b[g];return[[b],a]}f=M(a,b,c);b=f[0];a=f[1];return[[["name_tuple",h.find("part-name").text()||"",h.find("part-abbreviation").text()||""]].concat(b),a]}function S(a){var b,c;if(0==a.length)return[];var h=[];for(b=0;b<a.length;++b){var g=a[b];if(1==g.length)h.push(""+g[0]);else{h.push("(");for(c=0;c<g.length;++c)h.push(""+g[c]);h.push(")")}h.push("|")}h.splice(-1,1);1<a.length&&(h=["{"].concat(h).concat(["}"]));return h}function T(a,b,c,h,g,e){if("name_tuple"==a[0])h=h.shift(),
b[0]&&(a[1]=b[0]+":"+a[1],a[2]=b[1]+":"+a[2]),g.push(a),e.push.apply(e,S(h));else if(2==a.length&&"name_tuple"==a[0][0])h=h.shift(),c=["name_tuple","",""],c[1]=a[0][1]+":"+a[1][2],c[2]=a[0][2]+":"+a[1][3],g.push(c),e.push.apply(e,S(h));else{var f=a[a.length-1];b=f[0];var d=f[1];var n=f[2];f=f[3];d="yes"==d||c;e.push("brace"==b?"{":"[");for(c=0;c<a.length-1;++c)T(a[c],[n,f],d,h,g,e),d&&e.push("|");d&&e.splice(-1,1);e.push("brace"==b?"}":"]")}}function ha(a,b,c){for(var h=0,g=ia,e,f,d=[4,8,16];d.length;){var n=
d.shift(),p=0;for(e=0;e<b.length;++e){var l=b[e][a];for(f=0;f<l.length;++f){var m=l[f];m instanceof F||0==m.dur||(p+=L(m,c[e],n).length)}}p<g&&(h=n,g=p)}return h}function ja(a){for(var b="",c=a.children(),h=0;h<c.length;++h){var g=c[h];switch(g.tagName){case "elision":b+="~";break;case "text":b+=$(g).text().replace(/_/g,"\\_").replace(/-/g,"\\-").replace(/ /g,"~")}}if(!b)return b;c=a.find("syllabic").text();if("begin"==c||"middle"==c)b+="-";a.find("extend").length&&(b+="_");return b}function ka(a,
b,c,h){if(0!=c){b=b[c][h];var g=a[c][h];a=a[c-1][h];for(var e in a)if(c=a[e][1],!(e in g)&&c){c=b;h=[];for(var f=0;f<c.length;++f){var d=c[f];if(d instanceof E&&!d.grace){if("z"==d.ns[0]||"x"==d.ns[0])break;h.push("_")}}(c=h.join(" "))&&(g[e]=[c,0])}}}function la(a){var b={diamond:1,triangle:1,square:1,normal:1},c=ma,h,g="default",e={"default":[]},f={"default":[]};a=a.split("\n");for(h=0;h<a.length;++h){var d=a[h];if(0<=d.indexOf("I:percmap")){d=d.split(" ").map(function(a){return a.trim()});var n=
d[4];n in b&&(n=n+"+,"+n);d="%%map perc"+g+" "+d[1]+" print="+d[2]+" midi="+d[3]+" heads="+n;e[g].push(d)}0<=d.indexOf("%%MIDI")&&f[g].push(d);0<=d.indexOf("V:")&&(n=d.match(/V:\s*(\S+)/))&&(g=n[1],g in e||(e[g]=[],f[g]=[]))}b=Object.keys(e).sort();for(h=0;h<b.length;++h)c=c.concat(e[b[h]]);g="default";for(h=0;h<a.length;++h)d=a[h],0<=d.indexOf("I:percmap")||0<=d.indexOf("%%MIDI")||(0<=d.indexOf("V:")||0<=d.indexOf("K:")?((n=d.match(/V:\s*(\S+)/))&&(g=n[1]),c.push(d),g in f&&f[g].length&&(c=c.concat(f[g]),
delete f[g]),0<=d.indexOf("perc")&&-1==d.indexOf("map=")&&(d+=" map=perc"),0<=d.indexOf("map=perc")&&0<e[g].length&&c.push("%%voicemap perc"+g),0<=d.indexOf("map=off")&&c.push("%%voicemap")):c.push(d));return c.join("\n")}function O(a,b){var c=a;4<b&&(c=a.toLowerCase());5<b&&(c+=d(b-5,"'"));4>b&&(c+=d(4-b,","));return c}function N(a,b){if(a>b.divs/16)return 1;l("MuseScore bug: incorrect duration, smaller then 1/64! in measure %d, part %d",[b.ixm,b.ixp]);return 0}function w(a){this.slurBuf={};this.dirStk=
{};this.ingrace=0;this.grcNotes=[];this.msc=new x(a);this.unfold=a.u;this.ctf=a.c;this.gStfMap=[];this.midiMap=[];this.drumInst={};this.drumNotes={};this.instMid=[];this.midDflt=[-1,-1,-1,-91];this.msralts={};this.curalts={};this.stfMap={};this.vce2stf={};this.clefMap={};this.curClef={};this.stemDir={};this.clefOct={};this.curStf={};this.nolbrk=a.x;this.doPageFmt=1==a.p.length;this.tstep=a.t;this.dirtov1=a.v1;this.ped=!a.noped;this.wstems=a.stm;this.pedVce=null;this.repeat_str={};this.tabVceMap={};
this.koppen={};this.altkey=this.edo=0;this.note_alts=["=C ^C =D ^D =E =F ^F =G ^G =A ^A =B".split(" "),"^B _D ^^C _E _F ^E _G ^^F _A ^^G _B _C".split(" "),"__D ^^B __E __F ^^D __G ^^E __A _/A __B __C ^^A".split(" ")];this.step_map={C:0,D:2,E:4,F:5,G:7,A:9,B:11};this.temp=a.temp;this.musfin=a.fin;this.autoacc=0>a.fin;0>this.musfin&&(this.musfin=2);this.edo12alt={"flat-flat":-2,flat:-1,natural:0,sharp:1,"sharp-sharp":2};this.edo53alt={"quarter-sharp":1,"sharp-2":2,"sharp-3":3,sharp:4,"slash-quarter-sharp":5,
"slash-sharp":8,"sharp-sharp":9,natural:0,"quarter-flat":-1,"flat-2":-2,"flat-3":-3,"slash-flat":-4,flat:-5,"double-slash-flat":-8,"flat-flat":-9};this.edo36alt={"flat-down":-4,flat:-3,"flat-up":-2,"natural-down":-1,natural:0,"natural-up":1,"sharp-down":2,sharp:3,"sharp-up":4};this.edomap={"flat-down":-8,"flat-up":-3,"natural-down":-2,"natural-up":2,"sharp-down":3,"sharp-up":8};this.edomix={"flat-down":-4,"flat-up":-2,"natural-down":-1,"natural-up":1,"sharp-down":2,"sharp-up":4};this.note_type={whole:1,
half:2,quarter:4,eighth:8,"16th":16,"32nd":32,"64th":64}}var ia=Math.pow(2,53),U={"ornaments>trill-mark":"T","ornaments>mordent":"M","ornaments>inverted-mordent":"P","ornaments>turn":"!turn!","ornaments>inverted-turn":"!invertedturn!","technical>up-bow":"u","technical>down-bow":"v","technical>harmonic":"!open!","technical>open-string":"!open!","technical>stopped":"!plus!","technical>snap-pizzicato":"!snap!","technical>thumb-position":"!thumb!","articulations>accent":"!>!","articulations>strong-accent":"!^!",
"articulations>staccato":".","articulations>staccatissimo":"!wedge!","articulations>scoop":"!slide!",fermata:"!fermata!",arpeggiate:"!arpeggio!","articulations>tenuto":"!tenuto!","articulations>spiccato":"!wedge!","articulations>breath-mark":"!breath!","articulations>detached-legato":"!tenuto!."},V={p:"!p!",pp:"!pp!",ppp:"!ppp!",pppp:"!pppp!",f:"!f!",ff:"!ff!",fff:"!fff!",ffff:"!ffff!",mp:"!mp!",mf:"!mf!",sfz:"!sfz!"},ma='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(","),
W='%%beginsvg\n,<style type="text/css">\n,.bf {font-family:sans-serif; font-size:7px}\n,</style>\n,<defs>\n,<rect id="clr" x="-3" y="-1" width="6" height="5" fill="white"></rect>\n,<rect id="clr2" x="-3" y="-1" width="11" height="5" fill="white"></rect>\n'.split(","),u;I.prototype.inc=function(a,b){this.counters[a][b]=(this.counters[a][b]||0)+1};I.prototype.clear=function(a){a=Object.keys(a);var b=Array(a.length).fill(0);this.counters={note:k(a,b),nopr:k(a,b),nopt:k(a,b)}};I.prototype.getv=function(a,
b){return this.counters[a][b]};I.prototype.prcnt=function(a,b){for(var c in this.counters.note)0!=this.getv("nopr",c)&&l("part %d, voice %d has %d skipped non printable notes",[a,c,this.getv("nopr",c)]),0!=this.getv("nopt",c)&&l("part %d, voice %d has %d notes without pitch",[a,c,this.getv("nopt",c)]),0!=this.getv("note",c)||b||l("part %d, skipped empty voice %d",[a,c])};x.prototype.initVoices=function(a){this.vtimes={};this.voices={};this.lyrics={};this.chrdvs={};for(var b in this.vnums)this.vtimes[b]=
0,this.voices[b]=[],this.lyrics[b]=[],this.chrdvs[b]=[];a&&this.cnt.clear(this.vnums)};x.prototype.incTime=function(a){this.tijd+=a;0>this.tijd&&(this.tijd=0);this.tijd>this.maxtime&&(this.maxtime=this.tijd)};x.prototype.appendElemCv=function(a,b){for(var c in a)this.appendElem(c,b)};x.prototype.insertElem=function(a,b){b=new F(b);b.tijd=0;this.voices[a].unshift(b)};x.prototype.appendObj=function(a,b,c){b.tijd=this.tijd;this.voices[a].push(b);this.incTime(c);this.tijd>this.vtimes[a]&&(this.vtimes[a]=
this.tijd)};x.prototype.appendElemT=function(a,b,c){b=new F(b);b.tijd=c;this.voices[a].push(b)};x.prototype.appendElem=function(a,b,c){this.appendObj(a,new F(b),0);c&&this.cnt.inc("note",a)};x.prototype.appendNote=function(a,b,c){b.ns.push(b.ntdec+c);this.appendObj(a,b,parseInt(b.dur));this.lastnote=b;"z"!=c&&"x"!=c&&(this.cnt.inc("note",a),b.grace||this.lyrics[a].push(b.lyrs))};x.prototype.appendChordsym=function(a,b,c){b=new F(b);b.chsym=1;b.offset=c;this.appendObj(a,b,0);this.cnt.inc("note",a)};
x.prototype.getLastRec=function(a){return this.gMaten.length?(a=this.gMaten[this.gMaten.length-1][a],a[a.length-1]):null};x.prototype.getLastMelis=function(a,b){return this.gLyrics.length&&(a=this.gLyrics[this.gLyrics.length-1][a],b in a)?a[b][1]:0};x.prototype.addChord=function(a,b){for(var c=0;c<a.before.length;c++){var h=a.before[c];0>this.lastnote.before.indexOf(h)&&this.lastnote.before.push(h)}this.lastnote.ns.push(a.ntdec+b)};x.prototype.addBar=function(a,b,c,h){b.mdur&&this.maxtime>b.mdur&&
l("measure %d in part %d longer than metre",[b.ixm+1,b.ixp+1]);this.tijd=this.maxtime;for(var d in this.vnums){if(b.lline||b.lnum){var e=this.getLastRec(d);if(e){var f=e.str;b.lline&&(f=(f+b.lline).replace(/:\|:/g,"::").replace(/\|\|/g,"|"));3==this.nvlt?b.ixp+parseInt(d)==Math.min.apply(null,v(this.vnums))&&(f+=b.lnum):4==this.nvlt?parseInt(d)==Math.min.apply(null,v(this.vnums))&&(f+=b.lnum):b.lnum&&(f+=b.lnum,this.repbra=1);e.str=f}else b.lline&&this.insertElem(d,"|:")}a&&(e=this.getLastRec(d))&&
(e.str+=a);b.attr&&this.insertElem(d,""+b.attr);e=new F(" "+b.rline);e.isbar=1;this.appendObj(d,e,0);e=$jscomp.makeIterator(ea(this.voices[d],b,c,h,d));this.voices[d]=e.next().value;this.chrdvs[d]=e.next().value;e=this.lyrics[d];f={};for(var t=e.reduce(function(a,b){return a.concat(v(b))},[]),n=Math.max.apply(null,t.concat([0]));0<n;--n){t=e.map(function(a){return a[n]||""});var p=this.getLastMelis(d,n);f[n]=X(t,p)}this.lyrics[d]=f;this.nbr||ba(this.voices[d])}this.gMaten.push(this.voices);this.gLyrics.push(this.lyrics);
this.gChSyms.push(this.chrdvs);this.tijd=this.maxtime=0;this.initVoices()};x.prototype.outVoices=function(a,b){var c=a.map(function(a){return a.divs});a=a.map(function(a){return a.mtr});var h,d,e;var f={};var t=Math.min.apply(null,v(this.vnums)||[1]);for(d in this.vnums)if(0!=this.cnt.getv("note",d)||this.wev){var n=u.denL?u.denL:ha(d,this.gMaten,c);u.cmpL.push(n);var p=[],l={};for(e=0;e<this.gMaten.length;++e){var m=this.gMaten[e][d];var q=this.gChSyms[e][d];p.push(da(m,q,c[e],n,this.rbm,a[e]));
ka(this.gLyrics,this.gMaten,e,d);q=this.gLyrics[e][d];for(k in q)if(m=q[k],m=m[0],k in l){for(;l[k].length<e;)l[k].push("");l[k].push(m)}else l[k]=Array(e).fill("").concat([m])}for(k in l)m=l[k],n=p.length-m.length,l[k]=m.concat(Array(n).fill(""));u.add("V:"+this.vceCnt);this.repbra&&(1==this.nvlt&&1<this.vceCnt&&u.add("I:repbra 0"),2==this.nvlt&&parseInt(d)>t&&u.add("I:repbra 0"));0<this.cpl?this.bpl=0:0==this.bpl&&(this.cpl=100);for(n=0;p.length;){e=1;for(m=p[0];e<p.length&&!(0<this.cpl&&m.length+
p[e].length>=this.cpl)&&!(0<this.bpl&&e>=this.bpl);)m+=p[e],e+=1;n+=e;u.add(m+" %"+n);p.splice(0,e);q=H(l,1);for(h=0;h<q.length;++h){m=q[h];var k=m[0];m=m[1];u.add("w: "+m.slice(0,e).join("|")+"|");m.splice(0,e)}}f[d]=this.vceCnt;this.vceCnt+=1}this.gMaten=[];this.gLyrics=[];this.gChSyms=[];this.cnt.prcnt(b+1,this.wev);return f};J.prototype.add=function(a){this.outlist.push(a+"\n")};J.prototype.info=function(a,b){this.infolist.push(("undefined"==typeof b||b?"-- ":"")+a)};J.prototype.mkHeader=function(a,
b,c,h,d,e){var f=[],g=[],n;var p=a.slice();for(n=0;n<b.length;++n){var k=b[n];try{T(k,["",""],"",a,f,g)}catch(na){l("lousy musicxml: error in part-list",[])}}b=g.join(" ");a={};for(n=0;n<p.length&&n<f.length;++n){var z=p[n];k=f[n];var q=k[1];k=k[2];0!=z.length&&(z=z[0][0],q=q.replace(/\n/g,"\\n").replace(/\.:/g,".").replace(/^:|:$/g,""),k=k.replace(/\n/g,"\\n").replace(/\.:/g,".").replace(/^:|:$/g,""),a[z]=(q?'nm="'+q+'"':"")+(k?' snm="'+k+'"':""))}f=[m("X:%d\n%s\n%s",[this.X,this.title,-1<this.mnum?
"%%measurenb "+this.mnum+"\n":""])];e&&f.push("%%MIDI temperamentequal "+e+"\n");""!==this.scale&&f.push("%%scale "+this.scale+"\n");""!==this.pagewidth&&f.push("%%pagewidth "+this.pagewidth+"cm\n");""!==this.leftmargin&&f.push("%%leftmargin "+this.leftmargin+"cm\n");""!==this.rightmargin&&f.push("%%rightmargin "+this.rightmargin+"cm\n");b&&1<g.length&&f.push("%%score "+b+"\n");g=this.tempo?m("Q:%d/%d=%s\n",[this.tempo_units[0],this.tempo_units[1],this.tempo]):"";e=[];for(n=0;n<this.cmpL.length;++n)k=
this.cmpL[n],e[k]=(e[k]||0)+1;e=H(e);e=e[e.length-1][0];e=this.denL?this.denL:e;f.push(m("L:1/%d\n%sM:%s\n",[e,g,this.mtr]));f.push(m("I:linebreak $\nK:%s\n",[this.key]));this.stemless&&f.push("U:s=!stemless!\n");g=Object.keys(h).sort();for(n=0;n<g.length;++n)f=f.concat(h[g[n]]);this.dojef=0;g=$jscomp.makeIterator(this.clefs.keys());for(n=g.next();!n.done;n=g.next()){p=n.value;k=c[p-1];n=k[0];b=k[1];q=k[2];z=k[3];k=k.slice(4);var r=this.clefs.get(p);k.length&&0>r.indexOf("perc")&&(r=(r+" map=perc").trim());
f.push(m("V:%d %s %s\n",[p,r,a[p]||""]));p in h&&(f.push(m("%%voicemap tab%d\n",[p])),f.push("K:none\nM:none\n%%clef none\n%%staffscale 1.6\n%%flatbeams true\n%%stemdir down\n"));-1<r.indexOf("perc")&&f.push("K:none\n");1<this.volpan?(0<n&&n!=p&&f.push("%%MIDI channel "+n+"\n"),0<b&&f.push("%%MIDI program "+(b-1)+"\n"),0<=q&&f.push("%%MIDI control 7 "+q+"\n"),0<=z&&f.push("%%MIDI control 10 "+z+"\n")):0<this.volpan&&(k.length&&0<n&&f.push("%%MIDI channel "+n+"\n"),0<b&&f.push("%%MIDI program "+(b-
1)+"\n"));for(n=0;n<k.length;++n)if(b=k[n].nt,z=k[n].step,q=k[n].midi,(r=k[n].nhd)||(r="normal"),P(b)!=q||b!=z)0<this.volpan&&f.push("%%MIDI drummap "+b+" "+q+"\n"),f.push("I:percmap "+b+" "+z+" "+q+" "+r+"\n"),this.dojef=this.tstep;e!=this.cmpL[p-1]&&f.push("L:1/"+this.cmpL[p-1]+"\n")}this.outlist=f.concat(this.outlist);c=Object.keys(d).sort();if(c.length){var u=[];var D=this.shiftStem?'<g id="kop%s" class="bf"><use xlink:href="#clr"></use><text x="-2" y="3">%s</text></g>\n'.replace("-2","-5"):'<g id="kop%s" class="bf"><use xlink:href="#clr"></use><text x="-2" y="3">%s</text></g>\n',
C=this.shiftStem?'<g id="kop%s" class="bf"><use xlink:href="#clr2"></use><text x="-2" y="3">%s</text></g>\n'.replace("-2","-5"):'<g id="kop%s" class="bf"><use xlink:href="#clr2"></use><text x="-2" y="3">%s</text></g>\n';h=this.shiftStem?W.map(function(a){return a.replace("-3","-6")}):W;c.forEach(function(a){u.push(1<a.length?m(C,[a,a]):m(D,[a,a]))});this.outlist=h.concat(u,"</defs>\n%%endsvg\n",this.outlist)}};J.prototype.writeall=function(){var a=u.outlist.join("");this.dojef&&(a=la(a));return[a,
this.infolist.join("\n")]};w.prototype.matchSlur=function(a,b,c,h,d,e){if(-1!=["start","stop"].indexOf(a))if(b||(b="1"),b in this.slurBuf){var f=this.slurBuf[b];e=f[0];var g=f[1];f=f[2];a!=e?(c==g&&"start"==e&&(f.before.unshift("("),h.after+=")"),delete this.slurBuf[b]):(l("double slur numbers %s-%s in part %d, measure %d, voice %d note %s, first discarded",[a,b,this.msr.ixp+1,this.msr.ixm+1,c,h.ns]),this.slurBuf[b]=[a,c,h,d])}else this.slurBuf[b]=[a,c,h,d]};w.prototype.doNotations=function(a,b,c){for(var h=
Object.keys(U).sort(),g=0;g<h.length;++g){var e=h[g],f=U[e];b.find(e).length&&a.before.push(f)}g=b.find("ornaments>tremolo");g.length&&(e=g.attr("type"),h=d(parseInt(g.text()),"/"),"single"==e?a.before.unshift("!"+h+"!"):(a.fact=null,this.tstep?"stop"==e&&a.before.unshift("!trem"+g.text()+"!"):"start"==e&&a.before.unshift("!"+h+"-!")));h=b.find("technical>fingering");c||h.each(function(){a.before.push("!"+$(this).text()+"!")});h=b.find("technical>string");h.length&&c&&(this.tstep?(c=b.find("technical>fret"),
c.length&&(a.tab=[h.eq(0).text(),c.eq(0).text()])):h.each(function(){var b="!"+$(this).text()+"!";0>a.ntdec.indexOf(b)&&(a.ntdec+=b)}));c=b.find("ornaments>wavy-line");c=$jscomp.makeIterator(c.toArray());for(h=c.next();!h.done;h=c.next())switch(h=h.value,$(h).attr("type")){case "start":a.before.unshift("!trill(!");break;case "stop":a.after+="!trill)!"}c=b.find("glissando");0==c.length&&(c=b.find("slide"));c.length&&(b="wavy"==c.attr("line-type")?"~":"-","start"==c.attr("type")?a.before.unshift(m("!%s(!",
[b])):"stop"==c.attr("type")&&a.before.unshift(m("!%s)!",[b])))};w.prototype.tabnote=function(a,b,c,h,d){var e;var f=this.step_map[b]+parseInt(a||"0");11<f&&(c+=1,f-=12);0>f&&(--c,f+=12);a=d.tab[0];b=d.tab[1];for(e=0;4>e;++e){var g=this.note_alts[e%3][f];var n=c;-1<["^B","^^B"].indexOf(g)&&--n;-1<["_C","__C"].indexOf(g)&&(n+=1);if(-1<g.indexOf("/")||3==e)n=9;g=O(g,n);var p=this.tabmap[[h,g]]||["",""];n=p[0];p=p[1];if(!n)break;if(a==n)return g;3==e&&(l("rejected: voice %d note %s string %s fret %s remains: string %s fret %s",
[h,g,a,b,n,p]),d.tab=[n,p])}this.tabmap[[h,g]]=d.tab;return g};w.prototype.scanEdo=function(a){var b=a.find("accidental").toArray();b=b.concat(a.find("key-accidental").toArray());var c=!1,d=!1;b=$jscomp.makeIterator(b);for(var g=b.next();!g.done;g=b.next())g=A($(g.value).text()),g in this.edo12alt||(g in this.edo36alt&&(d=!0),g in this.edo53alt&&(c=!0));c&&d&&l("this score mixes edo53 and edo36 accidentals.",[]);d&&1==this.temp&&(c=!0,d=!1);this.edo=c?53:d?36:0;2==this.temp&&(this.edomap=this.edomix);
0<this.edo&&((a=a.find("identification>encoding>software").text())&&this.autoacc&&(0<=a.search(/abc2xml/i)&&(this.musfin=0),0<=a.search(/burak/i)&&(this.musfin=1),0<=a.search(/finale/i)&&(this.musfin=3)),u.info("encoder: "+["strict","burak","musescore","finale"][this.musfin]+", tuning: EDO"+this.edo+" ",""))};w.prototype.getcuralt=function(a,b,c,d){a=a+"#"+b+"#"+c;return a in this.curalts?this.curalts[a]:this.msralts[d]};w.prototype.alt2acc=function(a,b){/[+-]?[01]\.0/.test(a)&&(a=Math.round(a)+"");
if(0<=a.indexOf("."))return!a.match(/[+-]?0\.5/)||1<this.musfin?"":"0.5"==a?"quarter-sharp":"quarter-flat";b=$jscomp.makeIterator(Object.keys(this.edo12alt));for(var c=b.next();!c.done;c=b.next())if(c=c.value,this.edo12alt[c]==a)return c;return""};w.prototype.acc2abc=function(a){var b=0;switch(this.edo){case 53:var c=this.edo53alt[a];break;case 36:c=this.edo36alt[a];break;default:c=this.edo12alt[a]}void 0==c&&(c=this.edomap[a],b=1);return void 0==c?(l("unknown accidental %s",[a]),"="):0==c?"=":0<
this.edo?(a=0<c?"^"+c:"_"+-c,2==this.temp&&b&&(a+="/3"),36==this.edo&&(a=a.replace("3","")),a):["__","_","=","^","^^"][c+2]};w.prototype.ntAbc=function(a,b,c,d,g,e,f){b+=this.clefOct[this.curStf[d]]||0;var h=A(c.find("accidental").text()),n=c.find("pitch>alter").text();if(e.tab)return this.tabnote(n,a,b,d,e);f&&this.tstep&&(e=["__","_","","^","^^"][parseInt(n||"0")+2]+O(a,b),l("no string notation found for note %s in voice %d",[e,d]));b=O(a,b);e=b+"#"+d+"#"+g;if(h){if(3>this.musfin&&(n=this.altkey?
this.getcuralt(b,d,g,a):this.curalts[e],h==n&&!f))return b;this.curalts[e]=h;return b=this.acc2abc(h)+b}""==n?3>this.musfin&&(n=this.getcuralt(b,d,g,a))&&(1==this.musfin?h=this.ingrace?n:"natural":this.edo12alt[n]?h="natural":2>this.musfin&&(h="natural")):3>this.musfin&&(h=this.alt2acc(n));if(""!==h){n=this.getcuralt(b,d,g,a);if(h==n||"natural"==h&&!n||c.find("tie").add(c.find("notations>tied")).get().some(function(a){return"stop"==$(a).attr("type")}))return b;a=this.acc2abc(h);l("accidental %d added in part %d, measure %d, voice %d note %s",
[a,this.msr.ixp+1,this.msr.ixm+1,d+1,b]);this.curalts[e]=h;b=a+b}return b};w.prototype.doNote=function(a){var b=new E(0,null),c=parseInt(a.find("voice").text()||"1"),d=parseInt(a.find("staff").text()||"1");b.xmlvce=c;b.xmlstf=d;this.isSib&&(c+=100*d);var g=0<a.find("chord").length,e=a.find("pitch>step").text()||a.find("unpitched>display-step").text(),f=a.find("pitch>octave").text()||a.find("unpitched>display-octave").text(),l=0<a.find("rest").length,n=a.find("time-modification>actual-notes").text();
if(n){var p=a.find("time-modification>normal-notes").text();b.fact=[parseInt(n),parseInt(p)]}b.tup=a.find("notations>tuplet").map(function(){return $(this).attr("type")}).get();var k=a.find("duration").text();b.type=this.note_type[a.find("type").text()]||0;n=a.find("grace");b.grace=0<n.length;b.grace&&!g&&this.grcNotes.push(b);b.before=[""];b.after="";p=0==(this.curClef&&this.curClef[this.curStf[c]]||"").indexOf("tab");b.grace&&!this.ingrace&&(this.ingrace=1,b.before=["{"],"yes"!=n.attr("slash")||
p||b.before.push("/"));if(n=!b.grace&&this.ingrace)1==this.grcNotes.length&&(this.grcNotes[0].type*=2),this.grcNotes=[],this.ingrace=0,this.msc.lastnote.after+="}";if(!k||b.grace)k=0;if(!l&&"no"==a.attr("print-object")){if(g)return;l=1}b.dur=parseInt(k);l||e&&f||(this.msc.cnt.inc("nopt",c),f=5,e="E");k=a.find("notations");k.length&&this.doNotations(b,k,p);k=a.find("stem");!l&&k.length&&"none"==k.text()&&(!p||c in this.hasStems||this.tstep)&&(b.before.push("s"),u.stemless=1);k=a.find("accidental");
k.length&&"yes"==k.attr("parentheses")&&(b.ntdec+="!courtesy!");d=l?"no"==a.attr("print-object")||p?"x":"z":this.ntAbc(e,parseInt(f),a,c,d,b,p);if(a.find("unpitched").length){l=this.curClef[this.curStf[c]];e=Y(e,parseInt(f),l,this.tstep);f=a.find("instrument");f=f.length?f.attr("id"):"dummyId";f=this.drumInst[f]||P(d);l=a.find("notehead");p=l.text().replace(" ","-");"x"==p&&(d="^"+d.replace(/\^/g,"").replace(/_/g,""));if("circle-x"==p||"diamond"==p||"triangle"==p)d="_"+d.replace(/\^/g,"").replace(/_/g,
"");"yes"==l.attr("filled")&&(p+="+");"no"==l.attr("filled")&&(p+="-");this.drumNotes[c+";"+d]=[e,f,p]}e=a.find("tie").add(a.find("notations>tied")).get();e.some(function(a){return"start"==$(a).attr("type")})&&(d+="-");e=a.find("beam").map(function(){return $(this).text()}).get();b.beam=-1<e.indexOf("continue")||-1<e.indexOf("end")||b.grace;e=a.find("lyric");for(f=l=0;f<e.length;++f)p=$(e[f]),k=parseInt((p.attr("number")||"1").replace(/^.*verse/,"")),0==k?k=l+1:l=k,b.lyrs[k]=ja(p);e=a.find("stem").text();
!this.wstems||"up"!=e&&"down"!=e||e==this.stemDir[c]||(this.stemDir[c]=e,this.msc.appendElem(c,m("[I:stemdir %s]",[e])));g?this.msc.addChord(b,d):this.msc.appendNote(c,b,d);e=a.find("notations>slur");for(f=0;f<e.length;++f)a=$(e[f]),this.matchSlur(a.attr("type"),a.attr("number"),c,this.msc.lastnote,b.grace,n)};w.prototype.doAttr=function(a){var b,c;var d={C1:"alto1",C2:"alto2",C3:"alto",C4:"tenor",F4:"bass",F3:"bass3",G2:"treble",TAB:"tab",percussion:"perc"};if(b=a.find("divisions").text())this.msr.divs=
parseInt(b);b=parseInt(a.find("transpose>chromatic").text()||"0");var g=a.find("key>fifths").first().text();var e=a.find("key>key-step").first().text();var f=0==this.msc.tijd&&0==this.msr.ixm;if(g||e)(g?(g=Z(parseInt(g),a.find("key>mode").first().text()||"major"),e=$jscomp.makeIterator(g),g=e.next().value,this.msralts=e.next().value):(e=$jscomp.makeIterator(aa(a,this)),g=e.next().value,this.msralts=e.next().value,this.altkey=1),!f||b%12||"none"!=u.key)?g==u.key&&f||(this.msr.attr+="[K:"+g+"]"):u.key=
g;if(g=a.find("time>beats").text()){e=a.find("time>beat-type").text();var l=g+"/"+e;f?u.mtr=l:this.msr.attr+="[M:"+l+"]";this.msr.mtr=[parseInt(g),parseInt(e)]}this.msr.mdur=this.msr.divs*this.msr.mtr[0]*4/this.msr.mtr[1];var n=this;a.find("measure-style").each(function(){var a,b,c,d,h;var e=parseInt($(this).attr("number")||"1");var f=n.stfMap[e];$(this).find("measure-repeat").each(function(){a=$(this).attr("type");"start"==a?(n.repeat_str[e]=[n.msr.ixm,$(this).text()],f.forEach(function(a){n.msc.insertElem(a,
n.repeat_str[e])})):"stop"==a&&(b=n.repeat_str[e][0],d=n.repeat_str[e][1],c=n.msr.ixm-b,d?(h=d+" ",c/=parseInt(d)):h="",n.repeat_str[e][0]=m("[I:repeat %s%d]",[h,c]),delete n.repeat_str[e])})});(g=a.find("transpose>octave-change").text()||"")&&(b+=12*parseInt(g));g=a.find("clef");e={};l=a.find("staff-details");for(a=0;a<l.length;a++){var p=l.eq(a);e[p.attr("number")||1]=p}for(a=0;a<g.length;a++){var k=$(g[a]);l=parseInt(k.attr("number")||"1");var z=k.find("sign").text();p="percussion"!=z&&"TAB"!=
z?k.find("line").text()||"":"";p=d[z+p]||"";k=k.find("clef-octave-change").text()||"0";p+={"-2":"-15","-1":"-8",1:"+8",2:"+15"}[k]||"";this.clefOct[l]=-parseInt(k);b&&"TAB"!=z&&(p+=" transpose="+b);if(c=e[l]){if(k=c.find("staff-lines").text())z="3"==k&&"TAB"==z?"|||":k,p+=" stafflines="+z,this.stafflines=parseInt(k);var q=[];c.find("staff-tuning").each(function(){q.push($(this).find("tuning-step").text()+$(this).find("tuning-octave").text())});q.length&&(p+=m(" strings=%s",[q.join(",")]));(z=c.find("capo").text())&&
(p+=m(" capo=%s",[z]))}this.curClef[l]=p;if(f)this.clefMap[l]=p;else for(z=this.stfMap[l],c=0;c<z.length;++c){k=z[c];var r=new F("[K:"+p+"]",l);this.msc.appendObj(k,r,0)}}};w.prototype.findVoice=function(a,b){var c=b.eq(a);var d=parseInt(c.find("staff").text()||"1");var g=this.stfMap[d];g=g.length?g[0]:1;if(this.dirtov1)return{sn:d,v:g,v1:g};for(a+=1;a<b.length;++a){c=b.eq(a);if("note"==c[0].tagName)return b=parseInt(c.find("staff").text()||"1"),d=parseInt(c.find("voice").text()||"1"),this.isSib&&
(d+=100*b),b=this.vce2stf[d],{sn:b,v:d,v1:g};if("backup"==c[0].tagName)break}return{sn:d,v:g,v1:g}};w.prototype.doDirection=function(a,b,c){function d(a,b,c,d,h){b&&(c=0<=b.indexOf("!8v")?a.stfMap[h]:[c],c.forEach(function(c){null!=d?a.msc.appendElemT(c,b.replace("(",")").replace("ped","ped-up"),d):a.msc.appendElem(c,b)}))}function g(a,b,c,h){var f={down:"!8va(!",up:"!8vb(!",crescendo:"!<(!",diminuendo:"!>(!",start:"!ped!"};e=C.attr("type")||"";var g=b+(C.attr("number")||"1");if(e in f)if(f=f[e],
g in a.dirStk){var k=a.dirStk[g];delete a.dirStk[g];"stop"==k.type?d(a,f,c,k.tijd,h):(l("%s direction %s has no stop in part %d, measure %d, voice %d",[b,k.type,a.msr.ixp+1,a.msr.ixm+1,c+1]),a.dirStk[g]={type:e,vs:c})}else a.dirStk[g]={type:e,vs:c};else if("stop"==e)g in a.dirStk?(k=a.dirStk[g],delete a.dirStk[g],e=k.type,c=k.vs,"stop"==e?(l("%s direction %s has double stop in part %d, measure %d, voice %d",[b,e,a.msr.ixp+1,a.msr.ixm+1,c+1]),f=""):f=f[k.type].replace("(",")").replace("ped","ped-up")):
(a.dirStk[g]={type:"stop",tijd:a.msc.tijd},f="");else throw"wrong direction type";d(a,f,c,null,h)}var e,f,k,n="";var p=a.attr("placement");var r=this.findVoice(b,c);var z=r.sn;var q=r.v;var w=r.v1;var y="",D={dacapo:"D.C.",dalsegno:"D.S.",tocoda:"dacoda",fine:"fine",coda:"O",segno:"S"};var C=a.find("sound");if(C.length){var A=C.find("midi-instrument");if(A.length){var B=C.find("midi-instrument>midi-program").text();r=C.find("midi-instrument>midi-channel").text();for(k in this.vceInst)this.vceInst[k]==
A.attr("id")&&(q=k);(k=(B?B-1:r)+"")&&0<u.volpan&&this.msc.appendElem(q,"[I:MIDI= "+(B?"program":"channel")+" "+k+"]")}B=C.find("instrument-change>score-instrument");B.length&&(B=B.attr("id"),k=$jscomp.makeIterator(this.instMid[this.msr.ixp][B]),r=k.next().value,B=k.next().value,k.next(),k.next(),r=this.findVoice(b,c),b=$jscomp.makeIterator(["program",B-1]),B=b.next().value,k=b.next().value,0<u.volpan&&this.msc.appendElem(q,"[I:MIDI= "+B+" "+k+"]"));if(B=C.attr("tempo")){B=parseFloat(B).toFixed(0);
var x=[1,4]}for(v in D)if(C.attr(v)){y=D[v];break}}D=a.children("direction-type");for(b=0;b<D.length;++b){a=$(D[b]);var v={whole:[1,1],half:[1,2],quarter:[1,4],eighth:[1,8]};c=a.find("metronome");c.length&&(C=c.find("beat-unit").text()||"",x=C in v?v[C]:v.quarter,c.find("beat-unit-dot").length&&(x=K(3*x[0],2*x[1])),(v=c.find("per-minute").text().match(/[.\d]+/))&&(B=v[0]));C=a.find("wedge");C.length&&g(this,"wedge",q);v=a.find("words");0==v.length&&(v=a.find("rehearsal"));for(c=0;c<v.length;++c){if(y){this.msc.appendElem(q,
m("!%s!",[y]),1);break}var E="below"==p?"_":"^";k=$(v[c]);0>parseFloat(k.attr("default-y")||"0")&&(E="_");n+=k.text().replace(/"/g,'\\"').replace(/\n/g,"\\n")}n=n.trim();for(f in V)v=V[f],a.find("dynamics>"+f).length&&this.msc.appendElem(q,v,1);a.find("coda").length&&this.msc.appendElem(q,"O",1);a.find("segno").length&&this.msc.appendElem(q,"S",1);C=a.find("octave-shift");C.length&&g(this,"octave-shift",q,z);C=a.find("pedal");C.length&&this.ped&&(this.pedVce||(this.pedVce=q),g(this,"pedal",this.pedVce));
"diatonic fretting"==a.find("other-direction").text()&&(this.diafret=1)}B&&(B=parseFloat(B).toFixed(0),0==this.msc.tijd&&0==this.msr.ixm?(u.tempo=B,u.tempo_units=x):this.msc.appendElem(w,m("[Q:%d/%d=%s]",[x[0],x[1],B])));n&&this.msc.appendElem(q,'"'+E+n+'"',1)};w.prototype.doHarmony=function(a,b,c){c=this.findVoice(b,c).v;var d={major:"",minor:"m",augmented:"+",diminished:"dim",dominant:"7","half-diminished":"m7b5"};b={major:"maj",dominant:"",minor:"m",diminished:"dim",augmented:"+",suspended:"sus"};
var g={second:"2",fourth:"4",seventh:"7",sixth:"6",ninth:"9","11th":"11","13th":"13"};var e={1:"#",0:"","-1":"b"};var f=a.find("root>root-step","").text();var k=e[a.find("root>root-alter").text()]||"";var n="";var l=a.find("kind").text();l in d?l=d[l]:-1<l.indexOf("-")?(d=l.split("-"),l=d[0],d=d[1],l=(b[l]||"")+(g[d]||""),0==l.indexOf("sus")&&(n=l,l="")):"none"==l&&(l=a.find("kind").attr("text"));g=a.find("degree");for(b=0;b<g.length;++b)d=$(g[b]),l+=(e[d.find("degree-alter").text()]||"")+d.find("degree-value").text();
l=l.replace("79","9").replace("713","13").replace("maj6","6");e=a.find("bass>bass-step").text()+(e[a.find("bass>bass-alter").text()]||"");a=a.find("offset").text();this.msc.appendChordsym(c,'"'+f+k+l+n+(e&&"/"+e)+'"',a)};w.prototype.doBarline=function(a){var b=a.find("repeat"),c=0;b.length&&(c=b.attr("direction"));if(this.unfold)return c?"forward"==c?1:2:0;"right"==(a.attr("location")||"right")&&(b=a.find("bar-style").text(),"light-light"==b?this.msr.rline="||":"light-heavy"==b&&(this.msr.rline="|]"));
c&&("forward"==c?this.msr.lline=":":this.msr.rline=":|");a=a.find("ending");a.length&&("start"==a.attr("type")?(a=(a.attr("number")||"1").replace(/\./g,"").replace(/ /g,""),/^[\d,]+$/.test(a)||(a='"'+a.trim()+'"'),this.msr.lnum=a):"|"==this.msr.rline&&(this.msr.rline="||"));return 0};w.prototype.doPrint=function(a){if("yes"==a.attr("new-system")||"yes"==a.attr("new-page"))return this.nolbrk?"":"$"};w.prototype.doPartList=function(a){var b,c;var d=a.find("part-list>score-part");for(b=0;b<d.length;++b){var g=
d[b];var e={};var f=$(g).find("midi-instrument");for(g=0;g<f.length;++g){var k=$(f[g]);var l=["midi-channel","midi-program","volume","pan"];var p=[];for(c=0;c<l.length;++c){var m=l[c];p.push(k.find(m).text()||this.midDflt[c])}c=1*p[3];-90<=c&&90>=c&&(c=(c+90)/180*127);e[k.attr("id")]=[parseInt(p[0]),parseInt(p[1]),1.27*parseFloat(p[2]),c];(p=k.find("midi-unpitched").text())&&(this.drumInst[k.attr("id")]=p-1)}this.instMid.push(e)}a=a.find("part-list");p=fa(a);return M(p,{},[])[0]};w.prototype.mkTitle=
function(a){var b=[],c=[],d=[],g,e;var f=a.find("work>work-title").text().trim();var k=a.find("movement-title").text().trim();var n=a.find("identification>creator");for(g=0;g<n.length;++g){var p=$(n[g]);var m=p.text();p=p.attr("type");m&&(m=m.split("\n").map(function(a){return a.trim()}),"composer"==p?b.push.apply(b,m):("lyricist"==p||"transcriber"==p)&&c.push.apply(c,m))}n=a.find("identification>rights");for(g=0;g<n.length;++g)if(m=$(n[g]).text())m=m.split("\n").map(function(a){return a.trim()}),
c.push.apply(c,m);n=a.find("credit");for(g=0;g<n.length;++g){m="";p=$(n[g]).find("credit-words");for(e=0;e<p.length;++e)m+=$(p[e]).text();d.push(m.replace(/\s*[\r\n]\s*/g," "))}d=function(a){function e(a){return a&&-1<l.indexOf(a)}var h=[],g;for(g=0;g<d.length;++g){var l=d[g];6>a&&(l&&-1<f.indexOf(l)||l&&-1<k.indexOf(l))||5>a&&(l&&-1<b.indexOf(l)||l&&-1<c.indexOf(l))||4>a&&(f&&-1<l.indexOf(f)||k&&-1<l.indexOf(k))||3>a&&(b.some(e)||c.some(e))||2>a&&/^[\d\W]*$/.test(l)||h.push(l)}0==a&&f+k&&(h="");
return h}(this.ctf);f&&(f="T:"+f.replace(/\n/g,"\nT:")+"\n");k&&(f+="T:"+k.replace(/\n/g,"\nT:")+"\n");d.length&&(f+=d.map(function(a){return"T:"+a}).join("\n")+"\n");b.length&&(f+=b.map(function(a){return"C:"+a}).join("\n")+"\n");c.length&&(f+=c.map(function(a){return"Z:"+a}).join("\n")+"\n");f&&(u.title=f.substr(0,f.length-1));(this.isSib=0<=a.find("identification>encoding>software").text().indexOf("Sibelius"))&&l("Sibelius MusicXMl is unreliable",[])};w.prototype.doDefaults=function(a){if(this.doPageFmt){var b=
a.find("defaults");if(b.length){a=b.find("scaling>millimeters").text();var c=b.find("scaling>tenths").text();c=a/c/10;a=b.find("page-layout>page-width").text()*c;var d=b.find("page-layout>page-margins").first();b=d.find("left-margin").text();d=d.find("right-margin").text();var g=10*c/.2117;!u.scale&&g&&(u.scale=g.toFixed(2));!u.pagewidth&&a&&(u.pagewidth=a.toFixed(2));u.leftmargin||""==b||(u.leftmargin=(b*c).toFixed(2));u.rightmargin||""==d||(u.rightmargin=(d*c).toFixed(2))}}};w.prototype.locStaffMap=
function(a){var b={};this.vceInst={};this.msc.vnums={};this.hasStems={};this.stfMap={};this.clefMap={};a=a.find("measure>note");for(var c=0;c<a.length;c++){var d=$(a[c]),g=parseInt(d.find("voice").text()||"1");this.isSib&&(g+=100*(d.find("staff").text()||1));this.msc.vnums[g]=1;var e=parseInt(d.find("staff").text()||"1");this.stfMap[e]=[];if(g in b){var f=b[g];f[e]=(f[e]||0)+1}else f={},f[e]=1,b[g]=f;f=d.find("instrument");f.length&&(this.vceInst[g]=$(f).attr("id"));f=d.find("stem");0!=d.find("rest").length||
0!=f.length&&"none"==f.text()||(this.hasStems[g]=1)}for(g in b){a=[];c=b[g];for(e in c)a.push([c[e],e]);a.sort(function(a,b){return a[0]-b[0]});a=a[a.length-1][1];this.stfMap[a].push(g);this.vce2stf[g]=a;this.curStf[g]=a}};w.prototype.emptyStaves=function(a,b){var c=this,d=a[0];if(this.vce2stf=={})return a;var g=Object.keys(this.vce2stf).reduce(function(a,b){return Math.max(+a,+b)},[]),e=Object.entries(this.stfMap);e=e.filter(function(a){a=$jscomp.makeIterator(a);a.next();return 0==a.next().value.length});
e=e.map(function(a){a=$jscomp.makeIterator(a);var b=a.next().value;a.next();return b});if(0==e.length)return a;var f=$("<part></part>",d);f.attr("id",a.attr("id"));var k=$("<measure></measure>",d);e.forEach(function(e,h){var l=g+h+1,m=b.eq(0),n=a.find("divisions").text()||"1";h=$("<backup></backup>",d);var p=$("<duration>"+n+"</duration>",d);h.append(p);var r=$("<note></note",d);r.attr("print-object","no");p=$("<rest></rest>",d);p.attr("measure","yes");n=$("<duration>"+n+"</duration>");l=$("<voice>"+
l+"</voice>");e=$("<staff>"+e+"</staff>");r.append([p,n,l,e]);e=m.children();for(m=0;m<e.length&&"note"!=e[m].tagName;m++);e.splice(m,0,h[0]);e.splice(m,0,r[0]);k.append(e);f.append(k);f.append(b.slice(1));c.msc.wev=!0});this.locStaffMap(f);return f};w.prototype.addStaffMap=function(a){var b,c,d=[],g=Object.keys(this.stfMap).sort(function(a,b){return a-b});for(c=0;c<g.length;++c){var e=g[c];var f=this.stfMap[e];var k=[];var l=[];for(b=0;b<f.length;++b){var m=f[b];m in a&&(k.push(a[m]),l.push(void 0==
this.hasStems[m]))}if(k.length)for(d.push(k),f=(e in this.clefMap)?this.clefMap[e]:"treble",b=0;b<k.length;++b)m=k[b],e="",0==f.indexOf("tab")&&(l[b]&&0>f.indexOf("nostems")&&(e=" nostems"),this.diafret&&0>f.indexOf("diafret")&&(e+=" diafret")),u.clefs.set(m,f+e)}this.gStfMap.push(d)};w.prototype.addMidiMap=function(a,b){var c=this.instMid[a],d=Object.keys(c);var g=d.length?c[d[0]]:this.midDflt;a=[];var e=this;for(p in b){d=Object.keys(this.drumNotes).sort().filter(function(a){return a.split(";")[0]==
p});var f=d.map(function(a){return{nt:a.split(";")[1],step:e.drumNotes[a][0],midi:e.drumNotes[a][1],nhd:e.drumNotes[a][2]}});var k=b[p];d=this.vceInst[p]||"";d in c?a.push([k,c[d].concat(f)]):a.push([k,g.concat(f)])}a.sort(function(a,b){return a[0]-b[0]});a.forEach(function(a){e.midiMap.push(a[1])});g="E G B d f a c' e'".split(" ");var l="0 1- 1 1+ 2 3 3 4 4 5 6 6+ 7 8- 8 8+ 9 10 10 11 11 12 13 13+ 14".split(" ");d=Object.keys(this.tabmap).sort();for(c=0;c<d.length;++c){k=d[c];a=k.match(/(\d+),(.*)/);
var p=a[1];var r=a[2];f=this.tabmap[k][0];var u=this.tabmap[k][1];this.diafret&&(u=l[parseInt(u)]);k=b[p];f=this.stafflines-parseInt(f);a=this.tabVceMap[k]||[];a.push(m("%%map tab%d %s print=%s heads=kop%s\n",[k,r,g[f],u]));this.tabVceMap[k]=a;this.koppen[u]=1}};w.prototype.parse=function(a){var b={},c=$(a);this.scanEdo(c);this.mkTitle(c);this.doDefaults(c);a=this.doPartList(c);for(var d=c.find("part"),g=0;g<d.length;++g){var e=d.eq(g),f=e.find("measure");this.locStaffMap(e);e=this.emptyStaves(e,
f);f=e.find("measure");this.drumNotes={};this.clefOct={};this.curClef={};this.stemDir={};this.tabmap={};this.diafret=0;this.stafflines=5;this.msc.initVoices(1);this.maatRecs=[];this.msr={};for(var k=e=0,n=0;n<f.length;){var p=f.eq(n),r=0,v="";this.msr=new y(g,n,this.msr);this.curalts={};for(var q=p.children(),w=0;w<q.length;w++)switch(c=q.eq(w),c[0].tagName){case "note":this.doNote(c);break;case "attributes":this.doAttr(c);break;case "direction":this.doDirection(c,w,q);break;case "sound":this.doDirection(p,
w,q);break;case "harmony":this.doHarmony(c,w,q);break;case "barline":r=this.doBarline(c);break;case "backup":c=parseInt(c.find("duration").text());N(c,this.msr)&&this.msc.incTime(-c);break;case "forward":c=parseInt(c.find("duration").text());N(c,this.msr)&&this.msc.incTime(c);break;case "print":v=this.doPrint(c)}this.msc.addBar(v,this.msr,this.curStf,this.isSib);this.maatRecs.push(this.msr);1==r?(k=n,n+=1):2==r?1>e?(n=k,e+=1):(e=0,n+=1):n+=1}for(var x in this.repeat_str)f=this.repeat_str[x],f[0]=
m("[I:repeat %s %d]",[f[1],1]);f=this.msc.outVoices(this.maatRecs,g);this.addStaffMap(f);this.addMidiMap(g,f);for(x in f)b[x]=f[x]}Object.keys(b).length?u.mkHeader(this.gStfMap,a,this.midiMap,this.tabVceMap,this.koppen,this.edo):l("nothing written, %s has no notes ...",[u.fnmext])};vertaal=function(a,b){var c={u:0,b:0,n:0,c:0,v:0,d:0,m:0,x:0,t:0,v1:0,noped:0,stm:0,mnum:-1,temp:0,s:0,fin:-1,p:"f",rbm:0,nbr:0,wev:0},d;for(d in b)c[d]=b[d];c.p=c.p?c.p.split(","):[];u=new J(".abc","",0,c);(new w(c)).parse(a);
return u.writeall()}})();"undefined"!=typeof exports&&(exports.vertaal=vertaal,exports.xml2abc_VERSION=xml2abc_VERSION);
