//~ xmlplay, Revision: 188, Copyright (C) 2016-2025: Willem Vree, contributions Stéphane David.
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ GNU General Public License as published by the Free Software Foundation; either version 2 of
//~ the License, or (at your option) any later version.
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the GNU General Public License for more details. <http://www.gnu.org/licenses/gpl.html>.
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof f?a:new f(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)e.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var e=new b;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};f.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(v){g(v)}}:b}var d,g,e=new f(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return e};
f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(c)};f.resolve=c;f.reject=function(a){return new f(function(b,c){c(a)})};f.race=function(a){return new f(function(b,d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())c(e.value).callWhenSettled_(b,
d)})};f.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new f(function(a,f){function e(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(e(g.length-1),f),d=b.next();while(!d.done)})};return f},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var f=d.value}catch(e){return this.context_.yieldAllIterator_=null,this.context_.throw_(e),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,f){function e(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(e,f)}e(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.polyfill("globalThis",function(a){return a||$jscomp.global},"es_next","es3");$jscomp.polyfill("Math.log10",function(a){return a?a:function(a){return Math.log(a)/Math.LN10}},"es6","es3");$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6","es3");$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var f=b.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var e=b[c];if(e===a||Object.is(e,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,d){c=null!=c?c:function(a){return a};var b=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof e){a=e.call(a);for(var g=0;!(e=a.next()).done;)b.push(c.call(d,e.value,g++))}else for(e=a.length,g=0;g<e;g++)b.push(c.call(d,a[g],g));return b}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var f in d)$jscomp.owns(d,f)&&(a[f]=d[f])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
var audioCtx$$module$bouw$xmlplay_syn,opt$$module$bouw$xmlplay_syn,midiVol$$module$bouw$xmlplay_syn,midiPan$$module$bouw$xmlplay_syn,midiInstr$$module$bouw$xmlplay_syn,midiUsedArr$$module$bouw$xmlplay_syn,withRT$$module$bouw$xmlplay_syn,hasPan$$module$bouw$xmlplay_syn,hasLFO$$module$bouw$xmlplay_syn,hasFlt$$module$bouw$xmlplay_syn,hasVCF$$module$bouw$xmlplay_syn,instMap$$module$bouw$xmlplay_syn,cmpDlg$$module$bouw$xmlplay_syn,logerr$$module$bouw$xmlplay_syn;
function setSynVars$$module$bouw$xmlplay_syn(a,b,c,d,f,e,g,k,h,l,z,n,C,u){audioCtx$$module$bouw$xmlplay_syn=a;opt$$module$bouw$xmlplay_syn=b;midiVol$$module$bouw$xmlplay_syn=c;midiPan$$module$bouw$xmlplay_syn=d;midiInstr$$module$bouw$xmlplay_syn=f;midiUsedArr$$module$bouw$xmlplay_syn=e;withRT$$module$bouw$xmlplay_syn=g;hasPan$$module$bouw$xmlplay_syn=k;hasLFO$$module$bouw$xmlplay_syn=h;hasFlt$$module$bouw$xmlplay_syn=l;hasVCF$$module$bouw$xmlplay_syn=z;instMap$$module$bouw$xmlplay_syn=n;cmpDlg$$module$bouw$xmlplay_syn=
C;logerr$$module$bouw$xmlplay_syn=u}var params$$module$bouw$xmlplay_syn=[],rates$$module$bouw$xmlplay_syn=[],golven$$module$bouw$xmlplay_syn=[],liggend$$module$bouw$xmlplay_syn=[],midiLoaded$$module$bouw$xmlplay_syn={},instSf2Loaded$$module$bouw$xmlplay_syn={},instArr$$module$bouw$xmlplay_syn=[],inst_tb$$module$bouw$xmlplay_syn="acoustic_grand_piano bright_acoustic_piano electric_grand_piano honkytonk_piano electric_piano_1 electric_piano_2 harpsichord clavinet celesta glockenspiel music_box vibraphone marimba xylophone tubular_bells dulcimer drawbar_organ percussive_organ rock_organ church_organ reed_organ accordion harmonica tango_accordion acoustic_guitar_nylon acoustic_guitar_steel electric_guitar_jazz electric_guitar_clean electric_guitar_muted overdriven_guitar distortion_guitar guitar_harmonics acoustic_bass electric_bass_finger electric_bass_pick fretless_bass slap_bass_1 slap_bass_2 synth_bass_1 synth_bass_2 violin viola cello contrabass tremolo_strings pizzicato_strings orchestral_harp timpani string_ensemble_1 string_ensemble_2 synth_strings_1 synth_strings_2 choir_aahs voice_oohs synth_choir orchestra_hit trumpet trombone tuba muted_trumpet french_horn brass_section synth_brass_1 synth_brass_2 soprano_sax alto_sax tenor_sax baritone_sax oboe english_horn bassoon clarinet piccolo flute recorder pan_flute blown_bottle shakuhachi whistle ocarina lead_1_square lead_2_sawtooth lead_3_calliope lead_4_chiff lead_5_charang lead_6_voice lead_7_fifths lead_8_bass__lead pad_1_new_age pad_2_warm pad_3_polysynth pad_4_choir pad_5_bowed pad_6_metallic pad_7_halo pad_8_sweep fx_1_rain fx_2_soundtrack fx_3_crystal fx_4_atmosphere fx_5_brightness fx_6_goblins fx_7_echoes fx_8_scifi sitar banjo shamisen koto kalimba bagpipe fiddle shanai tinkle_bell agogo steel_drums woodblock taiko_drum melodic_tom synth_drum reverse_cymbal guitar_fret_noise breath_noise seashore bird_tweet telephone_ring helicopter applause gunshot".split(" ");
hasVCF$$module$bouw$xmlplay_syn=hasFlt$$module$bouw$xmlplay_syn=hasLFO$$module$bouw$xmlplay_syn=hasPan$$module$bouw$xmlplay_syn=1;var volCorJS$$module$bouw$xmlplay_syn=.015625,volCorSF$$module$bouw$xmlplay_syn=.5/60,gToSynth$$module$bouw$xmlplay_syn=0;function loginst$$module$bouw$xmlplay_syn(a){logerr$$module$bouw$xmlplay_syn(a);cmpDlg$$module$bouw$xmlplay_syn.innerHTML+='<div style="white-space: nowrap">'+a+"</div>"}
function logcmp$$module$bouw$xmlplay_syn(a){logerr$$module$bouw$xmlplay_syn(a);cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=a+"<br>"}
function speel$$module$bouw$xmlplay_syn(a,b,c,d,f,e,g,k,h){if(-1!=c)switch(opt$$module$bouw$xmlplay_syn.burak&&"//"==h.naam&&(h.naam="//burak"),h.naam){case "lowermordent":case "uppermordent":var l=$jscomp.makeIterator("lowermordent"==h.naam?h.nnr:h.nop);h=l.next().value;l=l.next().value;f*=e;e=f/4;100<e&&(e=100);speelhulp$$module$bouw$xmlplay_syn(a,b,c,d,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+e,b,h,l,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+2*e,b,c,d,f-2*e,g,k);break;case "//":e=f*e/4;speelhulp$$module$bouw$xmlplay_syn(a,
b,c,d,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+e,b,c,d,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+2*e,b,c,d,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+3*e,b,c,d,e,g,k);break;case "//burak":h.nop=[c,d];case "trill":f*=e;e=$jscomp.makeIterator(h.nop);h=e.next().value;l=e.next().value;for(e=a;e<a+f;)speelhulp$$module$bouw$xmlplay_syn(e,b,c,d,100,g,k),e+=100,speelhulp$$module$bouw$xmlplay_syn(e,b,h,l,100,g,k),e+=100;break;default:">"==h.naam&&(k*=1.4,127<k&&(k=127)),"dot"==h.naam&&96<f?f-=f/3:e=
192>=c.dur?1.3*e:1.1*e,speelhulp$$module$bouw$xmlplay_syn(a,b,c,d,f*e,g,k)}}function speelhulp$$module$bouw$xmlplay_syn(a,b,c,d,f,e,g){b=instMap$$module$bouw$xmlplay_syn[b];c+=opt$$module$bouw$xmlplay_syn.transMap[e]||0;b in instSf2Loaded$$module$bouw$xmlplay_syn&&withRT$$module$bouw$xmlplay_syn?opneer$$module$bouw$xmlplay_syn(b,c,d,a/1E3,(f-1)/1E3,e,g):b in instArr$$module$bouw$xmlplay_syn&&(b=[144,128*b+c,g],zend$$module$bouw$xmlplay_syn(b,a,e),b[2]=0,zend$$module$bouw$xmlplay_syn(b,a+f-1,e))}
function zend$$module$bouw$xmlplay_syn(a,b,c){if(0!=gToSynth$$module$bouw$xmlplay_syn){var d=a[0]&240,f=a[2];a=a[1];b/=1E3;128==d&&op$$module$bouw$xmlplay_syn(a,b);144==d&&(0<f?neer$$module$bouw$xmlplay_syn(a,f,b,c):op$$module$bouw$xmlplay_syn(a,b))}}
function neer$$module$bouw$xmlplay_syn(a,b,c,d){var f=midiVol$$module$bouw$xmlplay_syn[d]/127;d=(midiPan$$module$bouw$xmlplay_syn[d]-64)/64;var e=audioCtx$$module$bouw$xmlplay_syn.createBufferSource();e.buffer=golven$$module$bouw$xmlplay_syn[a];var g=audioCtx$$module$bouw$xmlplay_syn.createGain();g.gain.setValueAtTime(1E-5,c);b=b*f*volCorJS$$module$bouw$xmlplay_syn;0==b&&(b=1E-5);g.gain.exponentialRampToValueAtTime(b,c+.001);if(hasPan$$module$bouw$xmlplay_syn){var k=audioCtx$$module$bouw$xmlplay_syn.createStereoPanner();
k.pan.value=d}e.connect(k||g);k&&k.connect(g);g.connect(audioCtx$$module$bouw$xmlplay_syn.destination);e.start(c);liggend$$module$bouw$xmlplay_syn[a]=[e,g,b]}function op$$module$bouw$xmlplay_syn(a,b){var c=liggend$$module$bouw$xmlplay_syn[a],d=c[0],f=c[1];c=c[2];d&&(f.gain.setValueAtTime(c,b),f.gain.exponentialRampToValueAtTime(1E-5,b+.1),d.stop(b+.1),liggend$$module$bouw$xmlplay_syn[a]=void 0)}
function opneer$$module$bouw$xmlplay_syn(a,b,c,d,f,e,g){var k=params$$module$bouw$xmlplay_syn[a][b];if(k){var h=audioCtx$$module$bouw$xmlplay_syn.createBufferSource(),l=k.useflt,z=k.uselfo,n=k.useenv,C=midiVol$$module$bouw$xmlplay_syn[e]/127;e=(midiPan$$module$bouw$xmlplay_syn[e]-64)/64;h.buffer=k.buffer;k.loopStart&&(h.loop=!0,h.loopStart=k.loopStart,h.loopEnd=k.loopEnd);h.playbackRate.value=rates$$module$bouw$xmlplay_syn[a][b];h.detune.value=c;if(z){var u=audioCtx$$module$bouw$xmlplay_syn.createOscillator();
u.frequency.value=k.lfofreq;a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.value=k.lfo2vol;u.connect(a);var r=audioCtx$$module$bouw$xmlplay_syn.createGain();r.gain.value=1;a.connect(r.gain);a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.value=k.lfo2ptc;u.connect(a);a.connect(h.detune)}if(l){var v=audioCtx$$module$bouw$xmlplay_syn.createBiquadFilter();v.type="lowpass";v.frequency.value=k.filter}if(n){b=1;a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.setValueAtTime(0,d);
a.gain.linearRampToValueAtTime(b,d+k.envatt);c=k.envhld;var q=k.envdec;if(f>c){a.gain.setValueAtTime(b,d+c);if(f<q){var w=f-c;q=w/(q-c)*k.envsus}else w=q-c,q=k.envsus;b*=q;a.gain.linearRampToValueAtTime(b,d+c+w)}a.gain.setValueAtTime(b,d+f);b=d+f+b*k.envrel;a.gain.linearRampToValueAtTime(0,b);var y=audioCtx$$module$bouw$xmlplay_syn.createConstantSource();y.offset.value=k.env2flt;y.connect(a);a.connect(v.detune)}if(hasPan$$module$bouw$xmlplay_syn){var t=audioCtx$$module$bouw$xmlplay_syn.createStereoPanner();
t.pan.value=e}b=g*C*k.atten*volCorSF$$module$bouw$xmlplay_syn;0==b&&(b=1E-5);g=audioCtx$$module$bouw$xmlplay_syn.createGain();g.gain.setValueAtTime(1E-5,d);g.gain.exponentialRampToValueAtTime(b,d+k.attack);c=k.hold;q=k.decay;f>c&&(g.gain.setValueAtTime(b,d+c),f<q?(w=f-c,q=Math.pow(10,w/(q-c)*Math.log10(k.sustain))):(w=q-c,q=k.sustain),b*=q,g.gain.exponentialRampToValueAtTime(b,d+c+w));g.gain.setValueAtTime(b,d+f);b=d+f+(100+20*Math.log10(b))/100*k.release;g.gain.exponentialRampToValueAtTime(1E-5,
b);l?(h.connect(v),v.connect(t||g)):h.connect(t||g);t&&t.connect(g);z?(g.connect(r),r.connect(audioCtx$$module$bouw$xmlplay_syn.destination)):g.connect(audioCtx$$module$bouw$xmlplay_syn.destination);h.start(d);z&&u.start(d+k.lfodel);n&&y.start(d);h.stop(b);z&&u.stop(b);n&&y.stop(b)}}
function decode$$module$bouw$xmlplay_syn(a){return new Promise(function(b,c){for(var d=atob(a),f=new ArrayBuffer(d.length),e=new Uint8Array(f),g=0;g<d.length;g++)e[g]=d.charCodeAt(g);audioCtx$$module$bouw$xmlplay_syn.decodeAudioData(f,function(a){b(a)},function(a){c("error dedoding audio sample")})})}
function inst_create$$module$bouw$xmlplay_syn(a){var b,c,d,f,e,g,k,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:rates$$module$bouw$xmlplay_syn[a]=[],params$$module$bouw$xmlplay_syn[a]=[],b=0;case 2:if(!(b<instData.length)){l.jumpTo(0);break}c=instData[b];if(!c){l.jumpTo(3);break}d={attack:c.attack,hold:c.hold,decay:c.decay,sustain:c.sustain,release:c.release,atten:c.atten,filter:c.filter,lfodel:c.lfodel,lfofreq:c.lfofreq,lfo2ptc:c.lfo2ptc,lfo2vol:c.lfo2vol,
envatt:c.envatt,envhld:c.envhld,envdec:c.envdec,envsus:c.envsus,envrel:c.envrel,env2flt:c.env2flt,uselfo:hasLFO$$module$bouw$xmlplay_syn&&.008<c.lfofreq&&(0!=c.lfo2ptc||0!=c.lfo2vol),useflt:hasFlt$$module$bouw$xmlplay_syn&&16E3>c.filter,useenv:hasVCF$$module$bouw$xmlplay_syn&&16E3>c.filter&&0!=c.env2flt};c.loopStart&&(d.loopStart=c.loopStart,d.loopEnd=c.loopEnd);f=c.scale;e=c.tune;for(g=c.keyRangeLo;g<=c.keyRangeHi;g++)rates$$module$bouw$xmlplay_syn[a][g]=Math.pow(Math.pow(2,1/12),(g+e)*f),params$$module$bouw$xmlplay_syn[a][g]=
d;l.setCatchFinallyBlocks(5);k=d;return l.yield(decode$$module$bouw$xmlplay_syn(c.sample),7);case 7:k.buffer=l.yieldResult;l.leaveTryBlock(3);break;case 5:throw h=l.enterCatchBlock(),logcmp$$module$bouw$xmlplay_syn(h),h;case 3:++b,l.jumpTo(2)}})}
function laadJSfont$$module$bouw$xmlplay_syn(a,b){return new Promise(function(c,d){var f=document.createElement("script");f.src=b;f.onload=function(){c("ok");document.head.removeChild(f)};f.onerror=function(b){d("could not load instrument "+a)};document.head.appendChild(f)})}
function laadNoot$$module$bouw$xmlplay_syn(a){var b,c,d,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:cmpDlg$$module$bouw$xmlplay_syn.style.display="block",cmpDlg$$module$bouw$xmlplay_syn.innerHTML=withRT$$module$bouw$xmlplay_syn?"Loading SF2 fonts<br>":"Loading MIDI-js fonts<br>",b=[{url:opt$$module$bouw$xmlplay_syn.sf2url1,metRT:1},{url:opt$$module$bouw$xmlplay_syn.sf2url2,metRT:1},{url:opt$$module$bouw$xmlplay_syn.midijsUrl1,metRT:0},{url:opt$$module$bouw$xmlplay_syn.midijsUrl2,
metRT:0}],withRT$$module$bouw$xmlplay_syn||(b=b.slice(2)),c=$jscomp.makeIterator(b),d=c.next();case 2:if(d.done){g.jumpTo(4);break}f=d.value;g.setCatchFinallyBlocks(5);return g.yield(laadNoot2$$module$bouw$xmlplay_syn(f.url,f.metRT),7);case 7:return cmpDlg$$module$bouw$xmlplay_syn.style.display="none",logerr$$module$bouw$xmlplay_syn("fonts geladen"),a&&a(1),g.return();case 5:e=g.enterCatchBlock(),cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=e+"<br>",logerr$$module$bouw$xmlplay_syn(e);case 3:d=c.next();
g.jumpTo(2);break;case 4:logcmp$$module$bouw$xmlplay_syn(" ... give up"),g.jumpToEnd()}})}
function laadNoot2$$module$bouw$xmlplay_syn(a,b){function c(a,b){var c,d,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){switch(e.nextAddress){case 1:c=0;case 2:if(!(c<a.length)){e.jumpTo(0);break}d=a[c];if(d in instSf2Loaded$$module$bouw$xmlplay_syn){e.jumpTo(3);break}loginst$$module$bouw$xmlplay_syn(c+" loading instrument: "+d+(b?" from: "+b:""));f=b+"instr"+d+"mp3.js";return e.yield(laadJSfont$$module$bouw$xmlplay_syn(d,f),5);case 5:return e.yield(inst_create$$module$bouw$xmlplay_syn(d),
6);case 6:instSf2Loaded$$module$bouw$xmlplay_syn[d]=1;case 3:c++,e.jumpTo(2)}})}function d(a,b){var c,d,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:c=0;case 2:if(!(c<a.length)){g.jumpTo(0);break}d=a[c];if(d in instArr$$module$bouw$xmlplay_syn){g.jumpTo(3);break}loginst$$module$bouw$xmlplay_syn(c+" loading instrument: "+d+" from: "+b+"...");f=d in opt$$module$bouw$xmlplay_syn.instTab?opt$$module$bouw$xmlplay_syn.instTab[d]:inst_tb$$module$bouw$xmlplay_syn[d];
e=b+f+"-mp3.js";return g.yield(laadJSfont$$module$bouw$xmlplay_syn(d,e),5);case 5:instArr$$module$bouw$xmlplay_syn[d]=MIDI.Soundfont[f];case 3:++c,g.jumpTo(2)}})}function f(a){var b,c,d,f,e,g,h,k,w;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:b=0;case 2:if(!(b<a.length)){l.jumpTo(4);break}c=a[b];d=c>>7;f=c%128;e="C Db D Eb E F Gb G Ab A Bb B".split(" ");g=e[f%12];h=Math.floor(f/12)-1;k=instArr$$module$bouw$xmlplay_syn[d][g+h].split(",")[1];return l.yield(decode$$module$bouw$xmlplay_syn(k),
5);case 5:w=l.yieldResult;golven$$module$bouw$xmlplay_syn[c]=w;cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=", "+d+":"+f;midiLoaded$$module$bouw$xmlplay_syn[c]=1;++b;l.jumpTo(2);break;case 4:gToSynth$$module$bouw$xmlplay_syn=1,loginst$$module$bouw$xmlplay_syn("notes decoded"),l.jumpToEnd()}})}var e,g,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){if(1==h.nextAddress){e={};withRT$$module$bouw$xmlplay_syn=b;midiUsedArr$$module$bouw$xmlplay_syn.forEach(function(a){e[a>>7]=1});if(withRT$$module$bouw$xmlplay_syn)return h.yield(c(Object.keys(e),
a),0);if(g=document.getElementById("midijs"))g.checked="true";k=midiUsedArr$$module$bouw$xmlplay_syn.filter(function(a){return!(a in midiLoaded$$module$bouw$xmlplay_syn)});return h.yield(d(Object.keys(e),a),4)}cmpDlg$$module$bouw$xmlplay_syn.innerHTML+="decode notes:";return h.yield(f(k),0)})}var module$bouw$xmlplay_syn={};module$bouw$xmlplay_syn.laadNoot=laadNoot$$module$bouw$xmlplay_syn;module$bouw$xmlplay_syn.setSynVars=setSynVars$$module$bouw$xmlplay_syn;module$bouw$xmlplay_syn.speel=speel$$module$bouw$xmlplay_syn;var allNotes$$module$bouw$xmlplay_lib=[],midiVol$$module$bouw$xmlplay_lib=[],midiPan$$module$bouw$xmlplay_lib=[],midiInstr$$module$bouw$xmlplay_lib=[],midiUsedArr$$module$bouw$xmlplay_lib,gStaves$$module$bouw$xmlplay_lib,nVoices$$module$bouw$xmlplay_lib,stf2name$$module$bouw$xmlplay_lib,vce2stf$$module$bouw$xmlplay_lib,rMarks$$module$bouw$xmlplay_lib=[],isvgPrev$$module$bouw$xmlplay_lib=[],isvgAligned$$module$bouw$xmlplay_lib=-1,alignActive$$module$bouw$xmlplay_lib=0,abcElm$$module$bouw$xmlplay_lib,
iSeq$$module$bouw$xmlplay_lib,ntsSeq$$module$bouw$xmlplay_lib=[],barTimes$$module$bouw$xmlplay_lib={},deSvgs$$module$bouw$xmlplay_lib=[],deSvgGs$$module$bouw$xmlplay_lib=[],gScale$$module$bouw$xmlplay_lib=1,ntsPos$$module$bouw$xmlplay_lib={},stfPos$$module$bouw$xmlplay_lib=[],stfHgt$$module$bouw$xmlplay_lib=[],audioCtx$$module$bouw$xmlplay_lib,timer1$$module$bouw$xmlplay_lib,gAccTime$$module$bouw$xmlplay_lib,tmpElm$$module$bouw$xmlplay_lib,rolElm$$module$bouw$xmlplay_lib,metRects$$module$bouw$xmlplay_lib=
0,putMarkExt$$module$bouw$xmlplay_lib,startMaat$$module$bouw$xmlplay_lib=0;
function doModel$$module$bouw$xmlplay_lib(a,b,c,d,f,e,g){function k(a){var c=[];stf2name$$module$bouw$xmlplay_lib={};vce2stf$$module$bouw$xmlplay_lib={};a.forEach(function(a,d){c[a.st]?c[a.st].push(d):c[a.st]=[d];a.clef.clef_octave&&(C[d]=a.clef.clef_octave);stfHgt$$module$bouw$xmlplay_lib[a.st]=6*(a.stafflines||"|||||").length*(a.staffscale||1);midiVol$$module$bouw$xmlplay_lib[d]=a.midictl&&a.midictl[7];void 0==midiVol$$module$bouw$xmlplay_lib[d]&&(midiVol$$module$bouw$xmlplay_lib[d]=100);midiPan$$module$bouw$xmlplay_lib[d]=
a.midictl&&a.midictl[10];void 0==midiPan$$module$bouw$xmlplay_lib[d]&&(midiPan$$module$bouw$xmlplay_lib[d]=64);midiInstr$$module$bouw$xmlplay_lib[d]=a.instr?a.instr:0;d in b.instList&&(midiInstr$$module$bouw$xmlplay_lib[d]=b.instList[d]);vce2stf$$module$bouw$xmlplay_lib[d]=a.st;stf2name$$module$bouw$xmlplay_lib[a.st]||(stf2name$$module$bouw$xmlplay_lib[a.st]=a.nm||"")});return c}c=void 0===c?120:c;var h="",l=[3,0,4,1,5,2,6],z=[0,2,4,5,7,9,11],n=0,C=[],u=0;0<=a.indexOf("temperamentequal 53")&&(u=1);
g&&(metRects$$module$bouw$xmlplay_lib=1,putMarkExt$$module$bouw$xmlplay_lib=g);g=new Abc({img_out:null,errmsg:function(a,b,c){h+=a+"\n"},read_file:function(a){return""},anno_start:null,get_abcmodel:function(e,g,h){function q(a,b){var c,d={};var f=$jscomp.makeIterator(u?[48/53,-60/53]:[1,-1]);var e=f.next().value;f=f.next().value;b.extra&&(b=y[a]);var g=b.k_sf,h=b.k_a_acc;d[a]=[0,0,0,0,0,0,0];y[a]=b;b=(c=0<=g)?l.slice(0,g):l.slice(g);g=$jscomp.makeIterator(b);for(b=g.next();!b.done;b=g.next())b=b.value,
d[a][b]=c?e:f;if(h)for(e=$jscomp.makeIterator(h),b=e.next();!b.done;b=e.next())f=b.value,b=f.pit+19,b%=7,Number.isInteger(f.acc)?d[a][b]=f.acc:(h=$jscomp.makeIterator(f.acc),f=h.next().value,h=h.next().value,d[a][b]=f/h);p[a]=[];for(b=0;9>b;++b)p[a]=p[a].concat(d[a])}function w(a){var c="";if(a.a_dd)for(var d=$jscomp.makeIterator(a.a_dd),f=d.next();!f.done;f=d.next()){f=f.value;var e=N[f.name];e&&(b.dynvce?J[a.v]=e:gStaves$$module$bouw$xmlplay_lib[a.st].forEach(function(a){J[a]=e}));H.includes(f.name)&&
(c=f.name);"swing"==f.name&&(n=1);"swingoff"==f.name&&(n=0)}a.a_gch&&a.a_gch.forEach(function(a){/swing/i.test(a.text)&&(n=1);/straight/i.test(a.text)&&(n=0)});for(d=a.next;d&&8!=d.type&&10!=d.type;)d=d.next;192<=a.dur&&d&&192==d.dur&&0!=d.time%384&&n&&(a.dur+=64,d.time+=64,d.dur-=64);return c}function m(a,b,c){C[c]&&(b+=C[c]);if(void 0!=a.acc&&0!=a.acc)if(Number.isInteger(a.acc))p[c][b]=X[a.acc];else{var d=$jscomp.makeIterator(a.acc);a=d.next().value;d=d.next().value;p[c][b]=a/d}a=Math.floor(b/7);
d=b%7;a=12*a+z[d];u&&(d=(d+2)%7,a+=12*[0,9,13,22,31,35,44][d]/53-[0,2,3,5,7,8,10][d]);a+=p[c][b];b=Math.round(a);return[b,100*(a-b)]}function T(a,c,d,f,e){var g=m(c,d+1,f);c=m(c,d-1,f);e=e>b.arpmaxdur?b.arpmaxdur:e;return{naam:a,nop:g,nnr:c,ard:e}}function v(a,c,d,f){var e=d/(a.ns.length+1);b.burak&&(a.accia=!0);a.accia&&96<e&&(e=96);a=$jscomp.makeIterator(a.ns);for(var g=a.next();!g.done;g=a.next()){var h=g.value;h.t=c;f.push(h);g=h.ns[0].dur;if(g>e){g=e;h=$jscomp.makeIterator(h.ns);for(var l=h.next();!l.done;l=
h.next())l.value.dur=e}c+=g;d-=g}return[c,d]}function R(e,g){g=void 0===g?"ts_next":g;for(var h=[];e;e=e[g]){var l=[];switch(e.type){case 14:(l=e.tempo_notes)?(l=e.tempo_notes.reduce(function(a,b){return a+b}),c=e.tempo*l/384):(l=a.slice(e.istart,e.iend),(l=l.match(/\d+/))&&(c=1*l[0]));break;case 10:w(e);var k={t:e.time,mnum:-1,dur:e.dur,orn:{}};l.push(k);h.push({t:e.time,ix:e.istart,v:e.v,ns:l,inv:e.invis,tmp:c});break;case 8:var p=midiInstr$$module$bouw$xmlplay_lib[e.v];"p"==e.p_v.clef.clef_type&&
(p+=128);var H=w(e),n=e.time,z=e.dur,C=z/e.notes.length;if(G[e.v]){var t=$jscomp.makeIterator(v(G[e.v],n,z,h));n=t.next().value;z=t.next().value}for(t=0;t<e.notes.length;++t){var E=e.notes[t];var D=E.pit+19;var A=e.v;P=J[A]||80;var U=H?T(H,E,D,A,C):{};var B=$jscomp.makeIterator(m(E,D,A));k=B.next().value;B=B.next().value;if(d){var F=k+B/100;var x=Math.round(53*F/12+.25);console.log(x,F,E.midi)}F=e.p_v.map;128<=p&&"MIDIdrum"!=F&&(x=a.substring(e.istart,e.iend),x=x.match(/[=_^]*[A-Ga-g]/)[0],(x=f[F+
x])&&(k=x));"MIDIdrum"==F&&(k=E.midi);V[128*p+k]=1;k={t:n,inst:p,mnum:k,cnt:B,dur:z,velo:P,orn:U};D in r[A]?(x=r[A][D],n==x.t+x.dur?(x.dur+=z,E.tie_ty||delete r[A][D],k.mnum=-1):(console.log("wrong tie: ",A,x.mnum%127,x.t/384,x.dur),delete r[A][D],E.tie_ty&&(r[A][D]=k))):E.tie_ty&&(r[A][D]=k);l.push(k)}if(0==l.length)break;h.push({t:n,ix:e.istart,v:e.v,ns:l,stf:e.st,tmp:c});G[e.v]&&delete G[e.v];break;case 4:l=R(e.extra,"next");l.length&&(A=l[0].v,G[A]={ns:l},G[A].accia=e.sappo);break;case 5:q(e.v,
e);break;case 0:q(e.v,y[e.v]);h.push({t:e.time,ix:e.istart,v:e.v,bt:e.bar_type,tx:e.text});break;case 16:e.instr&&(midiInstr$$module$bouw$xmlplay_lib[e.v]=e.instr),7==e.ctrl&&(midiVol$$module$bouw$xmlplay_lib[e.v]=e.val),10==e.ctrl&&(midiPan$$module$bouw$xmlplay_lib[e.v]=e.val),e.v in b.instList&&0==e.time&&(midiInstr$$module$bouw$xmlplay_lib[e.v]=b.instList[e.v]),9==e.ctrl&&(u=53==e.val)}}return h}var H="trill lowermordent uppermordent // arpeggio dot >".split(" "),p={},y={},r={},G={},X={"-2":-2,
"-1":-1,0:0,1:1,2:2,3:0},N={ppp:16,pp:33,p:49,mp:64,mf:80,f:96,ff:112,fff:126},J=[],P;h=g[0].meter.a_meter;h.length&&parseInt(h[0].top);for(h=0;h<g.length;++h)q(h,g[h].key),r[h]={};var V={};nVoices$$module$bouw$xmlplay_lib=g.length;gStaves$$module$bouw$xmlplay_lib=k(g);allNotes$$module$bouw$xmlplay_lib=R(e);allNotes$$module$bouw$xmlplay_lib.sort(function(a,b){return a.t-b.t});midiUsedArr$$module$bouw$xmlplay_lib=Object.keys(V)}});g.tosvg("play","%%play");g.tosvg("abc2svg",a);""==h&&(h="no error");
e(h.trim());rMarks$$module$bouw$xmlplay_lib.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)});isvgPrev$$module$bouw$xmlplay_lib=[];e="#f9f #3cf #c99 #f66 #fc0 #cc0 #ccc".split(" ");for(g=0;g<nVoices$$module$bouw$xmlplay_lib;++g){var r=1<<g&b.curmsk?"0":"",v=document.createElementNS("http://www.w3.org/2000/svg","rect");v.setAttribute("fill",e[g%e.length]+r);v.setAttribute("fill-opacity","0.5");v.setAttribute("width","0");rMarks$$module$bouw$xmlplay_lib.push(v);isvgPrev$$module$bouw$xmlplay_lib.push(-1)}}
function doLayout$$module$bouw$xmlplay_lib(a,b,c,d,f,e,g,k,h,l){function z(b){var e=k();b.stopPropagation();var f=deSvgs$$module$bouw$xmlplay_lib.indexOf(this);if(!d||0>f)h(0),l(a,c,1);else{var g=b.clientX;g-=this.getBoundingClientRect().left;var m=g*gScale$$module$bouw$xmlplay_lib;if(m<w||m>y)h(0);else{!e&&c&&h(1);e=(b.clientY-this.getBoundingClientRect().top)*gScale$$module$bouw$xmlplay_lib;g=stfPos$$module$bouw$xmlplay_lib[f];for(b=0;b<g.length;b++)if(g[b]>e){t=b;break}for(b=0;b<ntsSeq$$module$bouw$xmlplay_lib.length;++b)if(e=
ntsSeq$$module$bouw$xmlplay_lib[b].xy)if(g=ntsSeq$$module$bouw$xmlplay_lib[b].vce,-1!=gStaves$$module$bouw$xmlplay_lib[t].indexOf(g)){var p=e[0];g=e[1];e=e[3];if(!(p<f)&&m<parseFloat(g)+e){iSeq$$module$bouw$xmlplay_lib=b;m=ntsSeq$$module$bouw$xmlplay_lib[b].t;for(isvgPrev$$module$bouw$xmlplay_lib.fill(-1);ntsSeq$$module$bouw$xmlplay_lib[b]&&ntsSeq$$module$bouw$xmlplay_lib[b].t==m;)putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[b]),b+=1;break}}}}}var n="",C="",u=0,r={},v,q,w=1E3,
y=0,t=0;abcElm$$module$bouw$xmlplay_lib=f;abcElm$$module$bouw$xmlplay_lib.style["scroll-behavior"]=b.nosm?"auto":"smooth";document.scrollingElement.style["scroll-behavior"]=b.nosm?"auto":"smooth";rolElm$$module$bouw$xmlplay_lib.style.visibility=b.noDash?"hidden":"visible";if(a){var B=new Abc({imagesize:'width="100%"',img_out:function(a){-1!=a.indexOf("<svg")&&(stfPos$$module$bouw$xmlplay_lib[u]=Object.keys(r),r={},u+=1,v<w&&(w=v),q>y&&(y=q));n+=a},errmsg:function(a,b,c){C+=a+"\n"},read_file:function(a){return""},
anno_start:function(a,b,c,d,e,f,g){if("note"==a||"rest"==a||"grace"==a)d=B.ax(d).toFixed(2),e=B.ay(e).toFixed(2),g=B.ah(g),ntsPos$$module$bouw$xmlplay_lib[b]=[u,d,e,f,g];"bar"==a&&(e=B.ay(e),g=B.ah(g),e=Math.round(e+g),r[e]=1,q=B.ax(d),v=B.ax(0))},get_abcmodel:null});B.tosvg("abc2svg",a);""==C&&(C="no error");e(C.trim());n&&(abcElm$$module$bouw$xmlplay_lib.innerHTML=n,deSvgs$$module$bouw$xmlplay_lib=Array.prototype.slice.call(abcElm$$module$bouw$xmlplay_lib.getElementsByTagName("svg")),deSvgs$$module$bouw$xmlplay_lib.forEach(function(a,
b){var c=a.querySelector(".g");deSvgGs$$module$bouw$xmlplay_lib[b]=c?c:a}),setScale$$module$bouw$xmlplay_lib(),deSvgs$$module$bouw$xmlplay_lib.forEach(function(a){g(a,"click",z)}),d&&(isvgAligned$$module$bouw$xmlplay_lib=-1,iSeq$$module$bouw$xmlplay_lib=0,mkNtsSeq$$module$bouw$xmlplay_lib(b.tomsr)),document.addEventListener("scrollend",eindRol$$module$bouw$xmlplay_lib))}}
function setScale$$module$bouw$xmlplay_lib(){if(0!=deSvgs$$module$bouw$xmlplay_lib.length){var a=deSvgs$$module$bouw$xmlplay_lib.length-1,b=deSvgs$$module$bouw$xmlplay_lib[a];var c=b.getBoundingClientRect().width;try{var d=b.viewBox.baseVal.width}catch(e){d=c}var f=(f=deSvgGs$$module$bouw$xmlplay_lib[a].transform)?f.baseVal:[];a=f.length?f.getItem(0).matrix.a:1;gScale$$module$bouw$xmlplay_lib=d/a/c}}
function mkNtsSeq$$module$bouw$xmlplay_lib(a){var b=0<iSeq$$module$bouw$xmlplay_lib&&ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib]?ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].t:0,c=1,d=0,f=0,e=0,g=0,k=0,h;ntsSeq$$module$bouw$xmlplay_lib=[];barTimes$$module$bouw$xmlplay_lib={};for(h=0;h<allNotes$$module$bouw$xmlplay_lib.length;++h){var l=allNotes$$module$bouw$xmlplay_lib[h];if(l.bt&&0==l.v){if(l.t in barTimes$$module$bouw$xmlplay_lib&&":"==l.bt[0])continue;if(1==
c&&":"==l.bt[0]&&l.t>e){h=f-1;c=2;d+=l.t-e;continue}2==c&&":"==l.bt[0]&&l.t>e&&(c=1);1==c&&":"==l.bt[l.bt.length-1]&&(f=h,e=l.t);g&&(l.tx||"|"!=l.bt)&&(g=0,d-=l.t-k);2==c&&"1"==l.tx&&(g=1,k=l.t)}g||(l.bt?barTimes$$module$bouw$xmlplay_lib[l.t]=l.t+d:ntsSeq$$module$bouw$xmlplay_lib.push({t:l.t+d,xy:metRects$$module$bouw$xmlplay_lib?l.ix:ntsPos$$module$bouw$xmlplay_lib[l.ix],ns:l.ns,vce:l.v,inv:l.inv,tmp:l.tmp}))}c=Object.keys(barTimes$$module$bouw$xmlplay_lib);0==b&&0<a&&(b=barTimes$$module$bouw$xmlplay_lib[c[a-
1]]);for(iSeq$$module$bouw$xmlplay_lib=0;iSeq$$module$bouw$xmlplay_lib<ntsSeq$$module$bouw$xmlplay_lib.length&&(l=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib],!(l.t>=b)||l.inv);++iSeq$$module$bouw$xmlplay_lib);iSeq$$module$bouw$xmlplay_lib==ntsSeq$$module$bouw$xmlplay_lib.length&&--iSeq$$module$bouw$xmlplay_lib;putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib])}
function rolRegel$$module$bouw$xmlplay_lib(a,b){var c=deSvgGs$$module$bouw$xmlplay_lib[b].getBoundingClientRect().top;c+=(stfPos$$module$bouw$xmlplay_lib[b][0]-stfHgt$$module$bouw$xmlplay_lib[0])/gScale$$module$bouw$xmlplay_lib;b=rolElm$$module$bouw$xmlplay_lib.getBoundingClientRect().bottom;c=Math.round(c-b);0!=c&&(a.scrollTop+=c)}
function alignSystem$$module$bouw$xmlplay_lib(a){if(a!=isvgAligned$$module$bouw$xmlplay_lib)if(isvgAligned$$module$bouw$xmlplay_lib=a,abcElm$$module$bouw$xmlplay_lib.clientHeight<abcElm$$module$bouw$xmlplay_lib.scrollHeight){alignActive$$module$bouw$xmlplay_lib=1;var b=abcElm$$module$bouw$xmlplay_lib.getBoundingClientRect();a=rolElm$$module$bouw$xmlplay_lib.getBoundingClientRect().bottom;a=Math.round(b.top-a)+100;if(b=0!=a)b=document.scrollingElement,b=b.clientHeight<b.scrollHeight;b?document.scrollingElement.scrollTop+=
a:eindRol$$module$bouw$xmlplay_lib()}else rolRegel$$module$bouw$xmlplay_lib(document.scrollingElement,a)}function eindRol$$module$bouw$xmlplay_lib(){alignActive$$module$bouw$xmlplay_lib&&(rolRegel$$module$bouw$xmlplay_lib(abcElm$$module$bouw$xmlplay_lib,isvgAligned$$module$bouw$xmlplay_lib),alignActive$$module$bouw$xmlplay_lib=0)}
function putMarkLoc$$module$bouw$xmlplay_lib(a,b){b=void 0===b?1:b;var c,d;if(metRects$$module$bouw$xmlplay_lib)putMarkExt$$module$bouw$xmlplay_lib(a);else{var f=rMarks$$module$bouw$xmlplay_lib[a.vce];if(c=a.xy){var e=c[0];var g=c[1];var k=c[2];var h=c[3];c=c[4];a.inv&&(c=h=0);2==b&&(isvgPrev$$module$bouw$xmlplay_lib[a.vce]=-1);e!=isvgPrev$$module$bouw$xmlplay_lib[a.vce]&&((d=f.parentNode)&&d.removeChild(f),d=deSvgGs$$module$bouw$xmlplay_lib[e],d.insertBefore(f,d.firstChild),isvgPrev$$module$bouw$xmlplay_lib[a.vce]=
e,0<b&&!a.inv&&alignSystem$$module$bouw$xmlplay_lib(e));f.setAttribute("x",g);f.setAttribute("y",k);f.setAttribute("width",h);f.setAttribute("height",c)}else f.setAttribute("width",0),f.setAttribute("height",0)}}
function plaatsLoper$$module$bouw$xmlplay_lib(a){for(var b=1,c,d=0;d<ntsSeq$$module$bouw$xmlplay_lib.length;++d){var f=ntsSeq$$module$bouw$xmlplay_lib[d];if(f.t>a){putMarkLoc$$module$bouw$xmlplay_lib(c,2);break}putMarkLoc$$module$bouw$xmlplay_lib(f,!1);f.t==a&&(b&&(iSeq$$module$bouw$xmlplay_lib=d,b=0),putMarkLoc$$module$bouw$xmlplay_lib(f,!1));f.xy&&(c=f)}}
function naarMaat$$module$bouw$xmlplay_lib(a){for(var b=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].ns[0].t,c=iSeq$$module$bouw$xmlplay_lib;c<ntsSeq$$module$bouw$xmlplay_lib.length&&0<=c;c+=a){var d=ntsSeq$$module$bouw$xmlplay_lib[c].ns[0].t;if(d!=b&&(d in barTimes$$module$bouw$xmlplay_lib||0==d)){plaatsLoper$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[c].t);break}}}
function regelOmhoog$$module$bouw$xmlplay_lib(a){var b,c=Infinity;for(b=iSeq$$module$bouw$xmlplay_lib;b<ntsSeq$$module$bouw$xmlplay_lib.length&&0<=b;b+=a)if(ntsSeq$$module$bouw$xmlplay_lib[b].xy&&!ntsSeq$$module$bouw$xmlplay_lib[b].inv)if(e){var d=$jscomp.makeIterator(ntsSeq$$module$bouw$xmlplay_lib[b].xy);var f=d.next().value;d=d.next().value;f==g+a&&Math.abs(e-d)<c&&(c=Math.abs(e-d),iSeq$$module$bouw$xmlplay_lib=b);if(1==a&&f>g+a)break;if(-1==a&&f<g+a)break}else{var e=$jscomp.makeIterator(ntsSeq$$module$bouw$xmlplay_lib[b].xy);
var g=e.next().value;e=e.next().value}plaatsLoper$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].t)}
function markeer$$module$bouw$xmlplay_lib(){if(audioCtx$$module$bouw$xmlplay_lib){var a=1E3*audioCtx$$module$bouw$xmlplay_lib.currentTime,b=gAccTime$$module$bouw$xmlplay_lib-a;a+=b;for(var c=0,d;0==c;){var f=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib];d=156.25/(f.tmp*tmpElm$$module$bouw$xmlplay_lib.value);iSeq$$module$bouw$xmlplay_lib==ntsSeq$$module$bouw$xmlplay_lib.length-1?(iSeq$$module$bouw$xmlplay_lib=-1,c=f.ns[0].dur+1E3):(c=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib+
1].t,c=(c-f.t)*d);var e="arpeggio"==f.ns[0].orn.naam?f.ns[0].orn.ard*d:0;f.ns.forEach(function(b,c){speel$$module$bouw$xmlplay_syn(a+c*e,b.inst,b.mnum,b.cnt,b.dur,d,f.vce,b.velo,b.orn)});setTimeout(function(a){putMarkLoc$$module$bouw$xmlplay_lib(a)},b,f);iSeq$$module$bouw$xmlplay_lib+=1}gAccTime$$module$bouw$xmlplay_lib+=c;clearTimeout(timer1$$module$bouw$xmlplay_lib);timer1$$module$bouw$xmlplay_lib=setTimeout(markeer$$module$bouw$xmlplay_lib,b+c-50)}else alert(alrtMsg2)}
function start_markeer$$module$bouw$xmlplay_lib(a,b){tmpElm$$module$bouw$xmlplay_lib=document.getElementById("tempo")||{value:1};audioCtx$$module$bouw$xmlplay_lib=a;gAccTime$$module$bouw$xmlplay_lib=1E3*audioCtx$$module$bouw$xmlplay_lib.currentTime;if(b){b=$jscomp.makeIterator(b.id.slice(1).split("_").map(function(a){return parseInt(a)}));a=b.next().value;b.next();b=0;for(var c=Infinity,d=0;d<ntsSeq$$module$bouw$xmlplay_lib.length;++d){var f=ntsSeq$$module$bouw$xmlplay_lib[d].xy-a;0<=f&&f<c&&(c=f,
b=d)}iSeq$$module$bouw$xmlplay_lib=b}markeer$$module$bouw$xmlplay_lib()}function stop_markeer$$module$bouw$xmlplay_lib(){clearTimeout(timer1$$module$bouw$xmlplay_lib)}function mapPerc$$module$bouw$xmlplay_lib(a){var b,c={},d={};a=a.split("\n");for(b=0;b<a.length;++b){var f=a[b];if(0<=f.indexOf("%%map")){var e=f.match(/%%map *(\S+) *(\S+).*midi=(\d+)/);f=f.match(/%%map *(\S+) /);if(e){f=e[1];var g=e[2];e=e[3];c[f+g]=parseInt(e)}else f&&(f=f[1],d[f]=1)}}return[d,c]}
function perc2map$$module$bouw$xmlplay_lib(a){var b={diamond:1,triangle:1,square:1,normal:1},c='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(","),
d,f="default",e={"default":[]},g={"default":[]};var k=a.split("\n");for(d=0;d<k.length;++d){var h=k[d];if(0<=h.indexOf("I:percmap")){h=h.split(/\s+/).map(function(a){return a.trim()});if(5>h.length)return a;var l=h[4];l in b&&(l=l+"+,"+l);h="%%map perc"+f+" "+h[1]+" print="+h[2]+" midi="+h[3]+" heads="+l;e[f].push(h)}0<=h.indexOf("%%MIDI")&&g[f].push(h);0<=h.indexOf("V:")&&(l=h.match(/V:\s*(\S+)/))&&(f=l[1],f in e||(e[f]=[],g[f]=[]))}a=Object.keys(e).sort();for(d=0;d<a.length;++d)c=c.concat(e[a[d]]);
f="default";for(d=0;d<k.length;++d)h=k[d],0<=h.indexOf("I:percmap")||0<=h.indexOf("%%MIDI")||(0<=h.indexOf("V:")||0<=h.indexOf("K:")?((l=h.match(/V:\s*(\S+)/))&&(f=l[1]),c.push(h),f in g&&g[f].length&&(c=c.concat(g[f]),delete g[f]),0<=h.indexOf("perc")&&-1==h.indexOf("map=")&&(h+=" map=perc"),0<=h.indexOf("map=perc")&&0<e[f].length&&c.push("%%voicemap perc"+f),0<=h.indexOf("map=off")&&c.push("%%voicemap")):c.push(h));return c.join("\n")}
function schuifLijn$$module$bouw$xmlplay_lib(a){function b(a){rolElm$$module$bouw$xmlplay_lib.style.top=a.clientY-15+"px"}function c(a){a.stopPropagation();rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointermove",b);rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointerup",c);rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointerleave",c);rolElm$$module$bouw$xmlplay_lib.style.cursor="initial";a=isvgAligned$$module$bouw$xmlplay_lib;isvgAligned$$module$bouw$xmlplay_lib=-1;alignSystem$$module$bouw$xmlplay_lib(a)}
rolElm$$module$bouw$xmlplay_lib.style.cursor="row-resize";rolElm$$module$bouw$xmlplay_lib.addEventListener("pointermove",b);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerup",c);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerleave",c)}
function addElms$$module$bouw$xmlplay_lib(){var a=document.createElement("style");a.innerHTML="#rollijn  { position:fixed; height:30px; width:100%; z-index:1; top: 30%; border-bottom: thin dashed black; touch-action: none; }\n#rollijn:hover { cursor: row-resize; background: rgba(0,255,0,0.3); }\n.dlog { display:none; background:lightblue; position:fixed; top: 50%; left: 50%; width:60%; padding:10px; transform: translate(-50%,-50%); z-index:9; overflow: auto; }\n";document.head.appendChild(a);rolElm$$module$bouw$xmlplay_lib=
document.createElement("div");rolElm$$module$bouw$xmlplay_lib.id="rollijn";document.body.appendChild(rolElm$$module$bouw$xmlplay_lib);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerdown",schuifLijn$$module$bouw$xmlplay_lib);a=document.createElement("div");a.id="comp";a.classList.add("dlog");document.body.appendChild(a)}
var module$bouw$xmlplay_lib={get iSeq(){return iSeq$$module$bouw$xmlplay_lib},get midiUsedArr(){return midiUsedArr$$module$bouw$xmlplay_lib},get ntsSeq(){return ntsSeq$$module$bouw$xmlplay_lib},get stf2name(){return stf2name$$module$bouw$xmlplay_lib},get vce2stf(){return vce2stf$$module$bouw$xmlplay_lib}};module$bouw$xmlplay_lib.addElms=addElms$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.doLayout=doLayout$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.doModel=doModel$$module$bouw$xmlplay_lib;
module$bouw$xmlplay_lib.mapPerc=mapPerc$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiInstr=midiInstr$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiPan=midiPan$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiVol=midiVol$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.mkNtsSeq=mkNtsSeq$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.naarMaat=naarMaat$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.perc2map=perc2map$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.putMarkLoc=putMarkLoc$$module$bouw$xmlplay_lib;
module$bouw$xmlplay_lib.regelOmhoog=regelOmhoog$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.setScale=setScale$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.start_markeer=start_markeer$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.stop_markeer=stop_markeer$$module$bouw$xmlplay_lib;var xmlplay_VERSION$$module$bouw$xmlplay2=188;
(function(){function a(a){Q.innerHTML+=a+"\n"}function b(b){var c=b.slice(0,4E3);0<=c.indexOf("X:")?e(b):-1==c.indexOf("<?xml ")?alert("not an xml file nor an abc file"):(b=(new window.DOMParser).parseFromString(b,"text/xml"),c={p:"f",t:1,u:0,v:3,m:2,mnum:0},ja&&(c.p=""),ka&&(c.x=1),m.rbm&&(c.rbm=1),b=vertaal(b,c),b[1]&&a(b[1]),e(b[0]))}function c(){var a,c=new FileReader;c.onload=function(a){b(c.result)};if(a=G?G[0]:W.files[0])U=a.name.split(".")[0],c.readAsText(a)}function d(c){var d,e,f,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:return d=
c[0].link,U=c[0].name.split(".")[0],I.style.display="block",a("link: "+d+"<br>"),h.setCatchFinallyBlocks(2),h.yield(fetch(d),4);case 4:return e=h.yieldResult,h.yield(e.text(),5);case 5:f=h.yieldResult;a("preload: "+f.length+" bytes");I.style.display="none";b(f);h.leaveTryBlock(0);break;case 2:g=h.enterCatchBlock();var l="fetch failed:"+g;a(l);I.innerHTML+=l+"<br>";h.jumpToEnd()}})}function f(a){a.stopPropagation();a.preventDefault();G=a.dataTransfer.files;this.classList.remove("indrag");c()}function e(b){null!=
b.match(new RegExp(/V:\w+\s*tab.*voicemap/,"s"))?delete abc2svg.mhooks.strtab:ca&&(abc2svg.mhooks.strtab=ca);0<=b.indexOf("I:percmap")&&(b=perc2map$$module$bouw$xmlplay_lib(b));if(0<=b.indexOf("%%map")){var c=$jscomp.makeIterator(mapPerc$$module$bouw$xmlplay_lib(b));var d=c.next().value;X=c.next().value}b.includes("temperamentequal")&&(b='%%beginsvg\n<defs>\n<text id="acc1_3" x="-1">&#xe261; <tspan x="-6" y="-4" style="font-size:14px">&#8593;</tspan></text>\n<text id="acc2_3" x="-1">&#xe262; <tspan x="-5" y="14" style="font-size:14px">&#8595;</tspan></text>\n<text id="acc4_3" x="-1">&#xe262; <tspan x="-5" y="-4" style="font-size:14px">&#8593;</tspan></text>\n<text id="acc-4_3" x="-2">&#xe260; <tspan x="-8.2" y="9" style="font-size:16px">&#8595;</tspan></text>\n<text id="acc-2_3" x="-1">&#xe260; <tspan x="-7.3" y="-1" style="font-size:16px">&#8593;</tspan></text>\n<text id="acc-1_3" x="-1">&#xe261; <tspan x="-2" y="12" style="font-size:14px">&#8595;</tspan></text>\n</defs>\n%%endsvg\n'+
b);c=T=b;for(var e in d){d="%%voicemap "+e;var f=d.replace("%voicemap","_________");c=c.replaceAll(d,f)}ha.value=m.speed;doModel$$module$bouw$xmlplay_lib(c,m,120,pa,X,a);N=midiVol$$module$bouw$xmlplay_lib;J=midiPan$$module$bouw$xmlplay_lib;P=midiInstr$$module$bouw$xmlplay_lib;F=midiUsedArr$$module$bouw$xmlplay_lib;ea=stf2name$$module$bouw$xmlplay_lib;V=vce2stf$$module$bouw$xmlplay_lib;da=Array(256).fill(1).map(function(a,b){return b});y();laadNoot$$module$bouw$xmlplay_syn();doLayout$$module$bouw$xmlplay_lib(b,
m,null,1,L,a,u,function(){return R},g);b=document.getElementById("schuivers");b.replaceChildren();for(e=0;e<N.length;++e)c=V[e],d=ea[c],c='<div class="schuif">\n    <div class="rij">\n        <div class="vol">\n            <label>Vol_XXX</label>\n            <input type="range" list="markers" min="0" max="127" step="1">\n            <div>0</div>\n        </div>\n        <div>&nbsp;</div>\n        <div class="pan">\n            <label>Pan_XXX</label>\n            <input type="range" list="markers" min="0" max="127" step="1">\n            <div>0</div>\n        </div>\n    </div>\n    <div class="instnum">Inst <input type=number value="22"></div>\n</div>\n'.replaceAll("XXX",
e+"<br>"+(d?d:c)),b.insertAdjacentHTML("beforeend",c);Array.from(document.querySelectorAll(".vol input")).forEach(function(a,b){a.value=N[b];q(a,b);a.addEventListener("change",function(c){q(a,b)})});Array.from(document.querySelectorAll(".pan input")).forEach(function(a,b){a.value=J[b];w(a,b);a.addEventListener("change",function(c){w(a,b)})});Array.from(document.querySelectorAll(".instnum input")).forEach(function(a,b){a.value=P[b];a.addEventListener("change",function(c){c=1*a.value;da[P[b]]=c;F.push(60+
(c<<7));y();laadNoot$$module$bouw$xmlplay_syn()})})}function g(){ntsSeq$$module$bouw$xmlplay_lib.length&&((R=1-R)?(D.value="Stop",E.style.display="none",start_markeer$$module$bouw$xmlplay_lib(p)):(D.value="Play",stop_markeer$$module$bouw$xmlplay_lib()))}function k(a){var b=a.key;if(document.activeElement==aa)"Enter"!=b&&" "!=b&&"m"!=b||t();else if("none"!=O.style.display)"Escape"!=b&&"m"!=b||t();else if(!(a.altKey||a.ctrlKey||a.shiftKey||"Tab"==b))switch(a.preventDefault(),b){case "ArrowLeft":case "Left":naarMaat$$module$bouw$xmlplay_lib(-1);
break;case "ArrowRight":case "Right":naarMaat$$module$bouw$xmlplay_lib(1);break;case "ArrowUp":case "Up":regelOmhoog$$module$bouw$xmlplay_lib(-1);break;case "ArrowDown":case "Down":regelOmhoog$$module$bouw$xmlplay_lib(1);break;case "m":t();break;case "t":I.style.display="none"==I.style.display?"block":"none";break;case " ":g()}}function h(c,d,e,f){var g,h,k,oa,S,ma,m,na;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:return g=c.match(/(.*\/)?([^/]*)$/),
h="./"+(g[1]?g[1]:""),k=document.getElementById("wait"),k.style.display="block",f.setCatchFinallyBlocks(2),f.yield(import(h+"parms.js"),4);case 4:oa=f.yieldResult;a("parms.js loaded");l(d,e,oa.parms);f.leaveTryBlock(3);break;case 2:S=f.enterCatchBlock(),"TypeError"==S.name?a("no parms.js present"):a("Error in parms.js: "+S.message),l(d,e,{});case 3:return f.setCatchFinallyBlocks(5),f.yield(fetch(c),7);case 7:return ma=f.yieldResult,f.yield(ma.text(),8);case 8:m=f.yieldResult;a("preload ok");b(m);
E.style.display="block";k.style.display="none";f.leaveTryBlock(0);break;case 5:throw na=f.enterCatchBlock(),k.innerHTML+="\npreload failed",na;}})}function l(a,b,c){var d={};Object.assign(d,a,c,b);void 0!=d.notationHeight&&(la=d.notationHeight);void 0!=d.fileURL&&(preload=d.fileURL);void 0!=d.speed&&(m.speed=d.speed);void 0!=d.noCur&&(m.curmsk=d.noCur);void 0!=d.noSave&&(document.getElementById("savlbl").style.display="none");void 0!=d.noMenu&&(document.getElementById("mbar").style.display="none");
void 0!=d.noErr&&(Q.style.display="none",Q.style.height="0px");void 0!=d.noPF&&(ja=1);void 0!=d.noLB&&(ka=1);void 0!=d.noRT&&(K=!d.noRT);void 0!=d.noDash&&(m.noDash=1);void 0==d.nosm&&H||(m.nosm=1);void 0!=d.rbm&&(m.rbm=d.rbm);void 0!=d.burak&&(m.burak=d.burak);void 0!=d.dynvce&&(m.dynvce=d.dynvce);void 0!=d.instTab&&(m.instTab=d.instTab);void 0!=d.sf2url1&&(m.sf2url1=d.sf2url1);void 0!=d.sf2url2&&(m.sf2url2=d.sf2url2);void 0!=d.midijsUrl1&&(m.midijsUrl1=d.midijsUrl1);void 0!=d.midijsUrl2&&(m.midijsUrl2=
d.midijsUrl2);if(void 0!=d.inst)for(a=$jscomp.makeIterator(d.inst),b=a.next();!b.done;b=a.next()){b=b.value;2==b.length&&b.push(0);var e=$jscomp.makeIterator(b);b=e.next().value;c=e.next().value;e=e.next().value;m.instList[b]=1*c;m.transMap[b]=1*e}void 0!=d.deb&&(pa=1);void 0!=d.arpmaxdur&&(m.arpmaxdur=d.arpmaxdur);void 0!=d.tomsr&&(m.tomsr=d.tomsr)}function z(){var a,b,c,d,e,f,g,k,m,p,n,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(S){c=b="";m={};a=window.location.href.replace("?dl=0",
"").split("?");if(1<a.length)for(d=a[1].split("&"),e=0;e<d.length;e++)g=d[e].replace(/d:(\w{15}\/[^.]+\.)/,"https://dl.dropboxusercontent.com/s/$1"),"noErr"==g?m.noErr=1:"noMenu"==g?m.noMenu=1:"noSave"==g?m.noSave=1:"noRT"==g?m.noRT=1:"noPF"==g?m.noPF=1:"noLB"==g?m.noLB=1:"noDash"==g?m.noDash=1:(k=g.match(/noCur=([\da-fA-F]{2})/))?m.noCur=parseInt(k[1],16):"nosm"==g?m.nosm=1:"ios"==g?H=x=ba=Z=Y=0:(k=g.match(/sf2=(\w+)/))?m.sf2url2=k[1]+"/":(k=g.match(/speed=([\d.]+)/))?m.speed=parseFloat(k[1]):(k=
g.match(/inst=([,-\d:]*)/))?m.inst=k[1].split(",").map(function(a){return a.split(":")}):"deb"==g?m.deb=1:"rbm"==g?m.rbm=1:"burak"==g?(m.rbm=1,m.burak=1):"dynvce"==g?m.dynvce=1:(k=g.match(/arp=([\d]+)/))?m.arpmaxdur=+k[1]:(k=g.match(/d:(\w{21}\/[\w.]+)/))?p="https://dl.dropboxusercontent.com/scl/fi/"+k[1]:(k=g.match(/rlkey=(\w+)/))?c=p+"?rlkey="+k[1]:(k=g.match(/tomsr=([\d]+)/))?m.tomsr=+k[1]:c=g;if(f=document.getElementById("parms"))f.style.display="none";n=f?JSON.parse(f.innerHTML):{};q=c.split("?")[0];
/(\.xml$)|(\.abc$)/.test(q)&&(b=c,c="");return b?S.yield(h(b,n,m),0):(l(n,m,{}),S.jumpTo(0))})}function n(){var a=Q.clientHeight;a=Math.round(100*a/document.documentElement.clientHeight);L.style.height=la-a+"%";ntsSeq$$module$bouw$xmlplay_lib.length&&putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib],2)}function C(){var b="",c="";if(T&&((new Abc({imagesize:'width="100%"',img_out:function(a){b+=a},errmsg:function(a,b,d){c+=a+"\n"},read_file:null,anno_start:null,
get_abcmodel:null})).tosvg("abc2svg",T),""==c&&(c="no error"),a(c.trim()),b)){var d='<html><meta charset="utf-8"><style>\n'+Array.from(document.styleSheets[1].rules).map(function(a){return a.cssText}).join("\n");d+="\n</style>\n<div>\n"+b+"\n</div></html>\n";var e=U+".html";try{var f=document.createElement("a");f.href=URL.createObjectURL(new Blob([d]));f.download=e;f.text="Save HTML file";document.getElementById("saveDiv").appendChild(f);f.click()}catch(qa){document.open("text/html"),document.write(d),
document.close(),setTimeout(function(){return alert('you can save this page with "save page as" in the browser file menu')},100)}}}function u(a,b,c){function d(b){a.removeEventListener("mousedown",d);a.removeEventListener("touchend",d);console.log("event listeners removed from "+a.nodeName+"#"+a.id);p&&"suspended"==p.state&&p.resume().then(function(){console.log("resuming audioContext")})}a.addEventListener("mousedown",d);a.addEventListener("touchend",d);a.addEventListener(b,c)}function r(){function b(a){M.checked=
!a;M.disabled=a;ia.style.color=a?"#aaa":"#000"}if("undefined"==typeof Dropbox){b(!0);var c=document.createElement("script");c.src="https://www.dropbox.com/static/api/2/dropins.js";c.onload=function(){b(!1);Dropbox.init({appKey:"ckknarypgq10318"});var a=Dropbox.createChooseButton({success:d,cancel:function(){},linkType:"direct",multiselect:!1,extensions:[".xml",".abc"]});fa.append(a);r()};c.onerror=function(){a("loading dropbox API failed")};document.head.appendChild(c)}else document.querySelector(".dropbox-dropin-btn").style.display=
M.checked?"inline-block":"none",W.style.display=M.checked?"none":"inline-block"}function v(){var a=document.body,b=a.requestFullscreen||a.mozRequestFullScreen||a.webkitRequestFullscreen,c=document.exitFullscreen||document.mozCancelFullScreen||document.webkitExitFullscreen;b&&c&&(A.checked?b.call(a):c.call(document))}function q(a,b){N[b]=1*a.value;a.parentElement.querySelector("div").innerHTML=a.value;y()}function w(a,b){J[b]=1*a.value;a.parentElement.querySelector("div").innerHTML=a.value;y()}function y(){setSynVars$$module$bouw$xmlplay_syn(p,
m,N,J,P,F,K,x,Y,Z,ba,da,I,a)}function t(a){a&&a.stopPropagation();a="none"==O.style.display;O.style.display=a?"flex":"none";aa.style.background=a?"#aaa":"";a&&D.focus()}function B(){A.checked=null!=(document.fullscreenElement||document.webkitFullscreenElement)}var m={speed:1,curmsk:0,sf2url1:"./",sf2url2:"",instTab:{},midijsUrl1:"./",midijsUrl2:"https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/",instList:{},transMap:{},burak:0,nosm:0,noDash:0,arpmaxdur:36,dynvce:0,tomsr:0},T,U,R=0,H,p=null,
F=[],la=100,G=null,X={},N=[],J=[],P=[],V={},ea={},L=null,I,Q,fa,W,ha,M,ia,aa,O,E,D,A,K=1,ja=0,ka=0,x=1,Y=1,Z=1,ba=1,da,pa=0,ca;document.addEventListener("DOMContentLoaded",function(){var a,b,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return addElms$$module$bouw$xmlplay_lib(),I=document.getElementById("comp"),L=document.getElementById("notation"),Q=document.getElementById("err"),fa=document.getElementById("abcfile"),W=document.getElementById("fknp"),ha=document.getElementById("tempo"),
E=document.getElementById("playbk"),D=document.getElementById("play"),A=document.getElementById("fscr"),ca=abc2svg.mhooks.strtab,u(D,"click",g),u(E,"click",g),W.addEventListener("change",c),document.getElementById("save").addEventListener("click",C),window.addEventListener("resize",function(){setScale$$module$bouw$xmlplay_lib();n()}),L.addEventListener("drop",f),L.addEventListener("dragover",function(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"}),L.addEventListener("dragenter",
function(){this.classList.add("indrag")}),L.addEventListener("dragleave",function(){this.classList.remove("indrag")}),M=document.getElementById("drpuse"),M.checked=!1,M.addEventListener("click",r),ia=document.getElementById("drplbl"),aa=document.getElementById("mbar"),O=document.getElementById("menu"),O.style.display="none",aa.addEventListener("click",function(a){return t(a)}),O.addEventListener("click",function(a){a.stopPropagation()}),H=CSS.supports("scroll-behavior","smooth"),a=window.AudioContext||
window.webkitAudioContext,p=void 0!=a?new a:null,e.yield(z(),2);n();b=["Your browser does not support:"];d=0;H||b.push("* smooth scrolling");p?(p.createStereoPanner||(x=0),p.createOscillator||(Y=0),p.createBiquadFilter||(Z=0),p.createConstantSource||(ba=0),x||b.push("* the StereoPanner element"),K&&!Y&&(b.push("* the Oscillator element"),d=1),K&&!Z&&(b.push("* the BiquadFilter element"),d=1),K&&!ba&&(b.push("* the ConstantSource element"),d=1),d&&(b.push("You are probably on iOS, which does not support the Web Audio API."),
b.push("Real time synthesis is switched off, falling back to MIDIjs"),K=0,document.getElementById("midijs").checked="true")):b.push("* the Web Audio API -> no sound");1<b.length&&alert(b.join("\n"));document.getElementById("verlab").innerHTML="<span>Version:</span>"+xmlplay_VERSION$$module$bouw$xmlplay2;A.addEventListener("change",v);document.body.addEventListener("fullscreenchange",B);document.body.addEventListener("webkitfullscreenchange",B);document.body.addEventListener("keydown",k);document.body.addEventListener("click",
function(a){"none"!=O.style.display&&t()});document.getElementById("midijs").addEventListener("click",function(a){K=0;y();laadNoot$$module$bouw$xmlplay_syn()});document.getElementById("sf2").addEventListener("click",function(a){K=1;y();laadNoot$$module$bouw$xmlplay_syn()});e.jumpToEnd()})})})();var module$bouw$xmlplay2={};
