//~ xmlplay_emb, Revision: 188, Copyright (C) 2016-2025: Willem Vree, contributions Stéphane David.
//~ This program is free software; you can redistribute it and/or modify it under the terms of the
//~ GNU General Public License as published by the Free Software Foundation; either version 2 of
//~ the License, or (at your option) any later version.
//~ This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//~ without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//~ See the GNU General Public License for more details. <http://www.gnu.org/licenses/gpl.html>.
'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var d=0;d<a.length;++d){var b=a[d];if(b&&b.Math==Math)return b}return globalThis};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,d){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(b){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(b||"")+"_"+d++,b)}var d=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in b||(b[f]={});b=b[f]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.matchAll",function(a){if(a)return a;$jscomp.initSymbolIterator();return function(a){if(a instanceof RegExp&&!a.global)throw new TypeError("RegExp passed into String.prototype.matchAll() must have global tag.");var b=new RegExp(a,a instanceof RegExp?void 0:"g"),d=this,f=!1,e={next:function(){var a={},c=b.lastIndex;if(f)return{value:void 0,done:!0};var e=b.exec(d);if(!e)return f=!0,{value:void 0,done:!0};b.lastIndex===c&&(b.lastIndex+=1);a.value=e;a.done=!1;return a}};
e[Symbol.iterator]=function(){return e};return e}},"es_next","es3");var audioCtx$$module$bouw$xmlplay_syn,opt$$module$bouw$xmlplay_syn,midiVol$$module$bouw$xmlplay_syn,midiPan$$module$bouw$xmlplay_syn,midiInstr$$module$bouw$xmlplay_syn,midiUsedArr$$module$bouw$xmlplay_syn,withRT$$module$bouw$xmlplay_syn,hasPan$$module$bouw$xmlplay_syn,hasLFO$$module$bouw$xmlplay_syn,hasFlt$$module$bouw$xmlplay_syn,hasVCF$$module$bouw$xmlplay_syn,instMap$$module$bouw$xmlplay_syn,cmpDlg$$module$bouw$xmlplay_syn,logerr$$module$bouw$xmlplay_syn;
function setSynVars$$module$bouw$xmlplay_syn(a,d,b,c,f,e,g,k,h,l,q,t,u,v){audioCtx$$module$bouw$xmlplay_syn=a;opt$$module$bouw$xmlplay_syn=d;midiVol$$module$bouw$xmlplay_syn=b;midiPan$$module$bouw$xmlplay_syn=c;midiInstr$$module$bouw$xmlplay_syn=f;midiUsedArr$$module$bouw$xmlplay_syn=e;withRT$$module$bouw$xmlplay_syn=g;hasPan$$module$bouw$xmlplay_syn=k;hasLFO$$module$bouw$xmlplay_syn=h;hasFlt$$module$bouw$xmlplay_syn=l;hasVCF$$module$bouw$xmlplay_syn=q;instMap$$module$bouw$xmlplay_syn=t;cmpDlg$$module$bouw$xmlplay_syn=
u;logerr$$module$bouw$xmlplay_syn=v}var params$$module$bouw$xmlplay_syn=[],rates$$module$bouw$xmlplay_syn=[],golven$$module$bouw$xmlplay_syn=[],liggend$$module$bouw$xmlplay_syn=[],midiLoaded$$module$bouw$xmlplay_syn={},instSf2Loaded$$module$bouw$xmlplay_syn={},instArr$$module$bouw$xmlplay_syn=[],inst_tb$$module$bouw$xmlplay_syn="acoustic_grand_piano bright_acoustic_piano electric_grand_piano honkytonk_piano electric_piano_1 electric_piano_2 harpsichord clavinet celesta glockenspiel music_box vibraphone marimba xylophone tubular_bells dulcimer drawbar_organ percussive_organ rock_organ church_organ reed_organ accordion harmonica tango_accordion acoustic_guitar_nylon acoustic_guitar_steel electric_guitar_jazz electric_guitar_clean electric_guitar_muted overdriven_guitar distortion_guitar guitar_harmonics acoustic_bass electric_bass_finger electric_bass_pick fretless_bass slap_bass_1 slap_bass_2 synth_bass_1 synth_bass_2 violin viola cello contrabass tremolo_strings pizzicato_strings orchestral_harp timpani string_ensemble_1 string_ensemble_2 synth_strings_1 synth_strings_2 choir_aahs voice_oohs synth_choir orchestra_hit trumpet trombone tuba muted_trumpet french_horn brass_section synth_brass_1 synth_brass_2 soprano_sax alto_sax tenor_sax baritone_sax oboe english_horn bassoon clarinet piccolo flute recorder pan_flute blown_bottle shakuhachi whistle ocarina lead_1_square lead_2_sawtooth lead_3_calliope lead_4_chiff lead_5_charang lead_6_voice lead_7_fifths lead_8_bass__lead pad_1_new_age pad_2_warm pad_3_polysynth pad_4_choir pad_5_bowed pad_6_metallic pad_7_halo pad_8_sweep fx_1_rain fx_2_soundtrack fx_3_crystal fx_4_atmosphere fx_5_brightness fx_6_goblins fx_7_echoes fx_8_scifi sitar banjo shamisen koto kalimba bagpipe fiddle shanai tinkle_bell agogo steel_drums woodblock taiko_drum melodic_tom synth_drum reverse_cymbal guitar_fret_noise breath_noise seashore bird_tweet telephone_ring helicopter applause gunshot".split(" ");
hasVCF$$module$bouw$xmlplay_syn=hasFlt$$module$bouw$xmlplay_syn=hasLFO$$module$bouw$xmlplay_syn=hasPan$$module$bouw$xmlplay_syn=1;const volCorJS$$module$bouw$xmlplay_syn=.015625,volCorSF$$module$bouw$xmlplay_syn=.5/60;var gToSynth$$module$bouw$xmlplay_syn=0;function loginst$$module$bouw$xmlplay_syn(a){logerr$$module$bouw$xmlplay_syn(a);cmpDlg$$module$bouw$xmlplay_syn.innerHTML+='<div style="white-space: nowrap">'+a+"</div>"}
function logcmp$$module$bouw$xmlplay_syn(a){logerr$$module$bouw$xmlplay_syn(a);cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=a+"<br>"}
function speel$$module$bouw$xmlplay_syn(a,d,b,c,f,e,g,k,h){if(-1!=b)switch(opt$$module$bouw$xmlplay_syn.burak&&"//"==h.naam&&(h.naam="//burak"),h.naam){case "lowermordent":case "uppermordent":var [l,q]="lowermordent"==h.naam?h.nnr:h.nop;f*=e;e=f/4;100<e&&(e=100);speelhulp$$module$bouw$xmlplay_syn(a,d,b,c,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+e,d,l,q,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+2*e,d,b,c,f-2*e,g,k);break;case "//":e=f*e/4;speelhulp$$module$bouw$xmlplay_syn(a,d,b,c,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+
e,d,b,c,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+2*e,d,b,c,e,g,k);speelhulp$$module$bouw$xmlplay_syn(a+3*e,d,b,c,e,g,k);break;case "//burak":h.nop=[b,c];case "trill":f*=e;var [l,q]=h.nop;for(e=a;e<a+f;)speelhulp$$module$bouw$xmlplay_syn(e,d,b,c,100,g,k),e+=100,speelhulp$$module$bouw$xmlplay_syn(e,d,l,q,100,g,k),e+=100;break;default:">"==h.naam&&(k*=1.4,127<k&&(k=127)),"dot"==h.naam&&96<f?f-=f/3:e=192>=b.dur?1.3*e:1.1*e,speelhulp$$module$bouw$xmlplay_syn(a,d,b,c,f*e,g,k)}}
function speelhulp$$module$bouw$xmlplay_syn(a,d,b,c,f,e,g){d=instMap$$module$bouw$xmlplay_syn[d];b+=opt$$module$bouw$xmlplay_syn.transMap[e]||0;d in instSf2Loaded$$module$bouw$xmlplay_syn&&withRT$$module$bouw$xmlplay_syn?opneer$$module$bouw$xmlplay_syn(d,b,c,a/1E3,(f-1)/1E3,e,g):d in instArr$$module$bouw$xmlplay_syn&&(d=[144,128*d+b,g],zend$$module$bouw$xmlplay_syn(d,a,e),d[2]=0,zend$$module$bouw$xmlplay_syn(d,a+f-1,e))}
function zend$$module$bouw$xmlplay_syn(a,d,b){if(0!=gToSynth$$module$bouw$xmlplay_syn){var c=a[0]&240,f=a[2];a=a[1];d/=1E3;128==c&&op$$module$bouw$xmlplay_syn(a,d);144==c&&(0<f?neer$$module$bouw$xmlplay_syn(a,f,d,b):op$$module$bouw$xmlplay_syn(a,d))}}
function neer$$module$bouw$xmlplay_syn(a,d,b,c){var f=midiVol$$module$bouw$xmlplay_syn[c]/127;c=(midiPan$$module$bouw$xmlplay_syn[c]-64)/64;var e=audioCtx$$module$bouw$xmlplay_syn.createBufferSource();e.buffer=golven$$module$bouw$xmlplay_syn[a];var g=audioCtx$$module$bouw$xmlplay_syn.createGain();g.gain.setValueAtTime(1E-5,b);d=d*f*volCorJS$$module$bouw$xmlplay_syn;0==d&&(d=1E-5);g.gain.exponentialRampToValueAtTime(d,b+.001);if(hasPan$$module$bouw$xmlplay_syn){var k=audioCtx$$module$bouw$xmlplay_syn.createStereoPanner();
k.pan.value=c}e.connect(k||g);k&&k.connect(g);g.connect(audioCtx$$module$bouw$xmlplay_syn.destination);e.start(b);liggend$$module$bouw$xmlplay_syn[a]=[e,g,d]}function op$$module$bouw$xmlplay_syn(a,d){var b=liggend$$module$bouw$xmlplay_syn[a],c=b[0],f=b[1];b=b[2];c&&(f.gain.setValueAtTime(b,d),f.gain.exponentialRampToValueAtTime(1E-5,d+.1),c.stop(d+.1),liggend$$module$bouw$xmlplay_syn[a]=void 0)}
function opneer$$module$bouw$xmlplay_syn(a,d,b,c,f,e,g){var k=params$$module$bouw$xmlplay_syn[a][d];if(k){var h=audioCtx$$module$bouw$xmlplay_syn.createBufferSource(),l=k.useflt,q=k.uselfo,t=k.useenv,u=midiVol$$module$bouw$xmlplay_syn[e]/127;e=(midiPan$$module$bouw$xmlplay_syn[e]-64)/64;h.buffer=k.buffer;k.loopStart&&(h.loop=!0,h.loopStart=k.loopStart,h.loopEnd=k.loopEnd);h.playbackRate.value=rates$$module$bouw$xmlplay_syn[a][d];h.detune.value=b;if(q){var v=audioCtx$$module$bouw$xmlplay_syn.createOscillator();
v.frequency.value=k.lfofreq;a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.value=k.lfo2vol;v.connect(a);var p=audioCtx$$module$bouw$xmlplay_syn.createGain();p.gain.value=1;a.connect(p.gain);a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.value=k.lfo2ptc;v.connect(a);a.connect(h.detune)}if(l){var r=audioCtx$$module$bouw$xmlplay_syn.createBiquadFilter();r.type="lowpass";r.frequency.value=k.filter}if(t){d=1;a=audioCtx$$module$bouw$xmlplay_syn.createGain();a.gain.setValueAtTime(0,c);
a.gain.linearRampToValueAtTime(d,c+k.envatt);b=k.envhld;var m=k.envdec;if(f>b){a.gain.setValueAtTime(d,c+b);if(f<m){var w=f-b;m=w/(m-b)*k.envsus}else w=m-b,m=k.envsus;d*=m;a.gain.linearRampToValueAtTime(d,c+b+w)}a.gain.setValueAtTime(d,c+f);d=c+f+d*k.envrel;a.gain.linearRampToValueAtTime(0,d);var x=audioCtx$$module$bouw$xmlplay_syn.createConstantSource();x.offset.value=k.env2flt;x.connect(a);a.connect(r.detune)}if(hasPan$$module$bouw$xmlplay_syn){var y=audioCtx$$module$bouw$xmlplay_syn.createStereoPanner();
y.pan.value=e}d=g*u*k.atten*volCorSF$$module$bouw$xmlplay_syn;0==d&&(d=1E-5);g=audioCtx$$module$bouw$xmlplay_syn.createGain();g.gain.setValueAtTime(1E-5,c);g.gain.exponentialRampToValueAtTime(d,c+k.attack);b=k.hold;m=k.decay;f>b&&(g.gain.setValueAtTime(d,c+b),f<m?(w=f-b,m=Math.pow(10,w/(m-b)*Math.log10(k.sustain))):(w=m-b,m=k.sustain),d*=m,g.gain.exponentialRampToValueAtTime(d,c+b+w));g.gain.setValueAtTime(d,c+f);d=c+f+(100+20*Math.log10(d))/100*k.release;g.gain.exponentialRampToValueAtTime(1E-5,
d);l?(h.connect(r),r.connect(y||g)):h.connect(y||g);y&&y.connect(g);q?(g.connect(p),p.connect(audioCtx$$module$bouw$xmlplay_syn.destination)):g.connect(audioCtx$$module$bouw$xmlplay_syn.destination);h.start(c);q&&v.start(c+k.lfodel);t&&x.start(c);h.stop(d);q&&v.stop(d);t&&x.stop(d)}}
function decode$$module$bouw$xmlplay_syn(a){return new Promise(function(d,b){for(var c=atob(a),f=new ArrayBuffer(c.length),e=new Uint8Array(f),g=0;g<c.length;g++)e[g]=c.charCodeAt(g);audioCtx$$module$bouw$xmlplay_syn.decodeAudioData(f,function(a){d(a)},function(a){b("error dedoding audio sample")})})}
async function inst_create$$module$bouw$xmlplay_syn(a){rates$$module$bouw$xmlplay_syn[a]=[];params$$module$bouw$xmlplay_syn[a]=[];for(var d=0;d<instData.length;++d){var b;if(b=instData[d]){var c={attack:b.attack,hold:b.hold,decay:b.decay,sustain:b.sustain,release:b.release,atten:b.atten,filter:b.filter,lfodel:b.lfodel,lfofreq:b.lfofreq,lfo2ptc:b.lfo2ptc,lfo2vol:b.lfo2vol,envatt:b.envatt,envhld:b.envhld,envdec:b.envdec,envsus:b.envsus,envrel:b.envrel,env2flt:b.env2flt,uselfo:hasLFO$$module$bouw$xmlplay_syn&&
.008<b.lfofreq&&(0!=b.lfo2ptc||0!=b.lfo2vol),useflt:hasFlt$$module$bouw$xmlplay_syn&&16E3>b.filter,useenv:hasVCF$$module$bouw$xmlplay_syn&&16E3>b.filter&&0!=b.env2flt};b.loopStart&&(c.loopStart=b.loopStart,c.loopEnd=b.loopEnd);var f=b.scale;var e=b.tune;for(var g=b.keyRangeLo;g<=b.keyRangeHi;g++)rates$$module$bouw$xmlplay_syn[a][g]=Math.pow(Math.pow(2,1/12),(g+e)*f),params$$module$bouw$xmlplay_syn[a][g]=c;try{c.buffer=await decode$$module$bouw$xmlplay_syn(b.sample)}catch(k){throw logcmp$$module$bouw$xmlplay_syn(k),
k;}}}}function laadJSfont$$module$bouw$xmlplay_syn(a,d){return new Promise(function(b,c){var f=document.createElement("script");f.src=d;f.onload=function(){b("ok");document.head.removeChild(f)};f.onerror=function(b){c("could not load instrument "+a)};document.head.appendChild(f)})}
async function laadNoot$$module$bouw$xmlplay_syn(a){cmpDlg$$module$bouw$xmlplay_syn.style.display="block";cmpDlg$$module$bouw$xmlplay_syn.innerHTML=withRT$$module$bouw$xmlplay_syn?"Loading SF2 fonts<br>":"Loading MIDI-js fonts<br>";var d=[{url:opt$$module$bouw$xmlplay_syn.sf2url1,metRT:1},{url:opt$$module$bouw$xmlplay_syn.sf2url2,metRT:1},{url:opt$$module$bouw$xmlplay_syn.midijsUrl1,metRT:0},{url:opt$$module$bouw$xmlplay_syn.midijsUrl2,metRT:0}];withRT$$module$bouw$xmlplay_syn||(d=d.slice(2));for(var b of d)try{await laadNoot2$$module$bouw$xmlplay_syn(b.url,
b.metRT);cmpDlg$$module$bouw$xmlplay_syn.style.display="none";logerr$$module$bouw$xmlplay_syn("fonts geladen");a&&a(1);return}catch(c){cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=c+"<br>",logerr$$module$bouw$xmlplay_syn(c)}logcmp$$module$bouw$xmlplay_syn(" ... give up")}
async function laadNoot2$$module$bouw$xmlplay_syn(a,d){async function b(a,b){for(var d=0;d<a.length;d++){var c=a[d];c in instSf2Loaded$$module$bouw$xmlplay_syn||(loginst$$module$bouw$xmlplay_syn(d+" loading instrument: "+c+(b?" from: "+b:"")),await laadJSfont$$module$bouw$xmlplay_syn(c,b+"instr"+c+"mp3.js"),await inst_create$$module$bouw$xmlplay_syn(c),instSf2Loaded$$module$bouw$xmlplay_syn[c]=1)}}async function c(a,b){for(var d=0;d<a.length;++d){var c=a[d];if(!(c in instArr$$module$bouw$xmlplay_syn)){loginst$$module$bouw$xmlplay_syn(d+
" loading instrument: "+c+" from: "+b+"...");var f=c in opt$$module$bouw$xmlplay_syn.instTab?opt$$module$bouw$xmlplay_syn.instTab[c]:inst_tb$$module$bouw$xmlplay_syn[c];await laadJSfont$$module$bouw$xmlplay_syn(c,b+f+"-mp3.js");instArr$$module$bouw$xmlplay_syn[c]=MIDI.Soundfont[f]}}}async function f(a){for(var b=0;b<a.length;++b){var d=a[b],c=d>>7,f=d%128,e=instArr$$module$bouw$xmlplay_syn[c]["C Db D Eb E F Gb G Ab A Bb B".split(" ")[f%12]+(Math.floor(f/12)-1)].split(",")[1];e=await decode$$module$bouw$xmlplay_syn(e);
golven$$module$bouw$xmlplay_syn[d]=e;cmpDlg$$module$bouw$xmlplay_syn.innerHTML+=", "+c+":"+f;midiLoaded$$module$bouw$xmlplay_syn[d]=1}gToSynth$$module$bouw$xmlplay_syn=1;loginst$$module$bouw$xmlplay_syn("notes decoded")}var e={};withRT$$module$bouw$xmlplay_syn=d;midiUsedArr$$module$bouw$xmlplay_syn.forEach(a=>{e[a>>7]=1});if(withRT$$module$bouw$xmlplay_syn)await b(Object.keys(e),a);else{if(d=document.getElementById("midijs"))d.checked="true";d=midiUsedArr$$module$bouw$xmlplay_syn.filter(function(a){return!(a in
midiLoaded$$module$bouw$xmlplay_syn)});await c(Object.keys(e),a);cmpDlg$$module$bouw$xmlplay_syn.innerHTML+="decode notes:";await f(d)}}var module$bouw$xmlplay_syn={};module$bouw$xmlplay_syn.laadNoot=laadNoot$$module$bouw$xmlplay_syn;module$bouw$xmlplay_syn.setSynVars=setSynVars$$module$bouw$xmlplay_syn;module$bouw$xmlplay_syn.speel=speel$$module$bouw$xmlplay_syn;var allNotes$$module$bouw$xmlplay_lib=[],midiVol$$module$bouw$xmlplay_lib=[],midiPan$$module$bouw$xmlplay_lib=[],midiInstr$$module$bouw$xmlplay_lib=[],midiUsedArr$$module$bouw$xmlplay_lib,gStaves$$module$bouw$xmlplay_lib,nVoices$$module$bouw$xmlplay_lib,stf2name$$module$bouw$xmlplay_lib,vce2stf$$module$bouw$xmlplay_lib,rMarks$$module$bouw$xmlplay_lib=[],isvgPrev$$module$bouw$xmlplay_lib=[],isvgAligned$$module$bouw$xmlplay_lib=-1,alignActive$$module$bouw$xmlplay_lib=0,abcElm$$module$bouw$xmlplay_lib,
iSeq$$module$bouw$xmlplay_lib,ntsSeq$$module$bouw$xmlplay_lib=[],barTimes$$module$bouw$xmlplay_lib={},deSvgs$$module$bouw$xmlplay_lib=[],deSvgGs$$module$bouw$xmlplay_lib=[],gScale$$module$bouw$xmlplay_lib=1,ntsPos$$module$bouw$xmlplay_lib={},stfPos$$module$bouw$xmlplay_lib=[],stfHgt$$module$bouw$xmlplay_lib=[],audioCtx$$module$bouw$xmlplay_lib,timer1$$module$bouw$xmlplay_lib,gAccTime$$module$bouw$xmlplay_lib,tmpElm$$module$bouw$xmlplay_lib,rolElm$$module$bouw$xmlplay_lib,metRects$$module$bouw$xmlplay_lib=
0,putMarkExt$$module$bouw$xmlplay_lib,startMaat$$module$bouw$xmlplay_lib=0;
function doModel$$module$bouw$xmlplay_lib(a,d,b=120,c,f,e,g){function k(a){var b=[];stf2name$$module$bouw$xmlplay_lib={};vce2stf$$module$bouw$xmlplay_lib={};a.forEach(function(a,c){b[a.st]?b[a.st].push(c):b[a.st]=[c];a.clef.clef_octave&&(u[c]=a.clef.clef_octave);stfHgt$$module$bouw$xmlplay_lib[a.st]=6*(a.stafflines||"|||||").length*(a.staffscale||1);midiVol$$module$bouw$xmlplay_lib[c]=a.midictl&&a.midictl[7];void 0==midiVol$$module$bouw$xmlplay_lib[c]&&(midiVol$$module$bouw$xmlplay_lib[c]=100);midiPan$$module$bouw$xmlplay_lib[c]=
a.midictl&&a.midictl[10];void 0==midiPan$$module$bouw$xmlplay_lib[c]&&(midiPan$$module$bouw$xmlplay_lib[c]=64);midiInstr$$module$bouw$xmlplay_lib[c]=a.instr?a.instr:0;c in d.instList&&(midiInstr$$module$bouw$xmlplay_lib[c]=d.instList[c]);vce2stf$$module$bouw$xmlplay_lib[c]=a.st;stf2name$$module$bouw$xmlplay_lib[a.st]||(stf2name$$module$bouw$xmlplay_lib[a.st]=a.nm||"")});return b}var h="",l=[3,0,4,1,5,2,6],q=[0,2,4,5,7,9,11],t=0,u=[],v=0;0<=a.indexOf("temperamentequal 53")&&(v=1);g&&(metRects$$module$bouw$xmlplay_lib=
1,putMarkExt$$module$bouw$xmlplay_lib=g);g=new Abc({img_out:null,errmsg:function(a,b,d){h+=a+"\n"},read_file:function(a){return""},anno_start:null,get_abcmodel:function(e,g,h){function m(a,b){var d,c={},[f,e]=v?[48/53,-60/53]:[1,-1];b.extra&&(b=w[a]);var g=b.k_sf;var K=b.k_a_acc;c[a]=[0,0,0,0,0,0,0];w[a]=b;g=(b=0<=g)?l.slice(0,g):l.slice(g);for(h of g)c[a][h]=b?f:e;if(K)for(d of K){var h=d.pit+19;h%=7;if(Number.isInteger(d.acc))c[a][h]=d.acc;else{var [z,k]=d.acc;c[a][h]=z/k}}n[a]=[];for(d=0;9>d;++d)n[a]=
n[a].concat(c[a])}function r(a){var b="";if(a.a_dd)for(var c of a.a_dd){var f=O[c.name];f&&(d.dynvce?J[a.v]=f:gStaves$$module$bouw$xmlplay_lib[a.st].forEach(function(a){J[a]=f}));C.includes(c.name)&&(b=c.name);"swing"==c.name&&(t=1);"swingoff"==c.name&&(t=0)}a.a_gch&&a.a_gch.forEach(function(a){/swing/i.test(a.text)&&(t=1);/straight/i.test(a.text)&&(t=0)});for(c=a.next;c&&8!=c.type&&10!=c.type;)c=c.next;192<=a.dur&&c&&192==c.dur&&0!=c.time%384&&t&&(a.dur+=64,c.time+=64,c.dur-=64);return b}function z(a,
b,d){u[d]&&(b+=u[d]);if(void 0!=a.acc&&0!=a.acc)if(Number.isInteger(a.acc))n[d][b]=P[a.acc];else{var [c,f]=a.acc;n[d][b]=c/f}a=Math.floor(b/7);var e=b%7;a=12*a+q[e];v&&(e=(e+2)%7,a+=12*[0,9,13,22,31,35,44][e]/53-[0,2,3,5,7,8,10][e]);a+=n[d][b];b=Math.round(a);return[b,100*(a-b)]}function I(a,b,c,f,e){var g=z(b,c+1,f);b=z(b,c-1,f);e=e>d.arpmaxdur?d.arpmaxdur:e;return{naam:a,nop:g,nnr:b,ard:e}}function H(a,b,c,f){var e=c/(a.ns.length+1);d.burak&&(a.accia=!0);a.accia&&96<e&&(e=96);for(var g of a.ns){g.t=
b;f.push(g);a=g.ns[0].dur;if(a>e){a=e;for(var h of g.ns)h.dur=e}b+=a;c-=a}return[b,c]}function L(e,g="ts_next"){for(var h=[];e;e=e[g]){var k,l,C=[];switch(e.type){case 14:(k=e.tempo_notes)?(k=e.tempo_notes.reduce(function(a,b){return a+b}),b=e.tempo*k/384):(k=a.slice(e.istart,e.iend),(k=k.match(/\d+/))&&(b=1*k[0]));break;case 10:r(e);var n={t:e.time,mnum:-1,dur:e.dur,orn:{}};C.push(n);h.push({t:e.time,ix:e.istart,v:e.v,ns:C,inv:e.invis,tmp:b});break;case 8:var q=midiInstr$$module$bouw$xmlplay_lib[e.v];
"p"==e.p_v.clef.clef_type&&(q+=128);var t=r(e),u=e.time,F=e.dur,B=F/e.notes.length;x[e.v]&&([u,F]=H(x[e.v],u,F,h));for(k=0;k<e.notes.length;++k){var y=e.notes[k];var E=y.pit+19;var D=e.v;M=J[D]||80;var Q=t?I(t,y,E,D,B):{};[n,l]=z(y,E,D);if(c){var G=n+l/100;var A=Math.round(53*G/12+.25);console.log(A,G,y.midi)}G=e.p_v.map;128<=q&&"MIDIdrum"!=G&&(A=a.substring(e.istart,e.iend),A=A.match(/[=_^]*[A-Ga-g]/)[0],(A=f[G+A])&&(n=A));"MIDIdrum"==G&&(n=y.midi);N[128*q+n]=1;n={t:u,inst:q,mnum:n,cnt:l,dur:F,velo:M,
orn:Q};E in p[D]?(A=p[D][E],u==A.t+A.dur?(A.dur+=F,y.tie_ty||delete p[D][E],n.mnum=-1):(console.log("wrong tie: ",D,A.mnum%127,A.t/384,A.dur),delete p[D][E],y.tie_ty&&(p[D][E]=n))):y.tie_ty&&(p[D][E]=n);C.push(n)}if(0==C.length)break;h.push({t:u,ix:e.istart,v:e.v,ns:C,stf:e.st,tmp:b});x[e.v]&&delete x[e.v];break;case 4:C=L(e.extra,"next");C.length&&(D=C[0].v,x[D]={ns:C},x[D].accia=e.sappo);break;case 5:m(e.v,e);break;case 0:m(e.v,w[e.v]);h.push({t:e.time,ix:e.istart,v:e.v,bt:e.bar_type,tx:e.text});
break;case 16:e.instr&&(midiInstr$$module$bouw$xmlplay_lib[e.v]=e.instr),7==e.ctrl&&(midiVol$$module$bouw$xmlplay_lib[e.v]=e.val),10==e.ctrl&&(midiPan$$module$bouw$xmlplay_lib[e.v]=e.val),e.v in d.instList&&0==e.time&&(midiInstr$$module$bouw$xmlplay_lib[e.v]=d.instList[e.v]),9==e.ctrl&&(v=53==e.val)}}return h}const C="trill lowermordent uppermordent // arpeggio dot >".split(" ");var n={},w={},p={},x={},P={"-2":-2,"-1":-1,0:0,1:1,2:2,3:0},O={ppp:16,pp:33,p:49,mp:64,mf:80,f:96,ff:112,fff:126},J=[],
M;h=g[0].meter.a_meter;h.length&&parseInt(h[0].top);for(h=0;h<g.length;++h)m(h,g[h].key),p[h]={};var N={};nVoices$$module$bouw$xmlplay_lib=g.length;gStaves$$module$bouw$xmlplay_lib=k(g);allNotes$$module$bouw$xmlplay_lib=L(e);allNotes$$module$bouw$xmlplay_lib.sort((a,b)=>a.t-b.t);midiUsedArr$$module$bouw$xmlplay_lib=Object.keys(N)}});g.tosvg("play","%%play");g.tosvg("abc2svg",a);""==h&&(h="no error");e(h.trim());rMarks$$module$bouw$xmlplay_lib.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)});
isvgPrev$$module$bouw$xmlplay_lib=[];e="#f9f #3cf #c99 #f66 #fc0 #cc0 #ccc".split(" ");for(g=0;g<nVoices$$module$bouw$xmlplay_lib;++g){var p=1<<g&d.curmsk?"0":"",r=document.createElementNS("http://www.w3.org/2000/svg","rect");r.setAttribute("fill",e[g%e.length]+p);r.setAttribute("fill-opacity","0.5");r.setAttribute("width","0");rMarks$$module$bouw$xmlplay_lib.push(r);isvgPrev$$module$bouw$xmlplay_lib.push(-1)}}
function doLayout$$module$bouw$xmlplay_lib(a,d,b,c,f,e,g,k,h,l){function q(d){var e=k();d.stopPropagation();var f=deSvgs$$module$bouw$xmlplay_lib.indexOf(this);if(!c||0>f)h(0),l(a,b,1);else{var g=d.clientX;g-=this.getBoundingClientRect().left;var z=g*gScale$$module$bouw$xmlplay_lib;if(z<w||z>x)h(0);else{!e&&b&&h(1);e=(d.clientY-this.getBoundingClientRect().top)*gScale$$module$bouw$xmlplay_lib;g=stfPos$$module$bouw$xmlplay_lib[f];for(d=0;d<g.length;d++)if(g[d]>e){y=d;break}for(d=0;d<ntsSeq$$module$bouw$xmlplay_lib.length;++d)if(e=
ntsSeq$$module$bouw$xmlplay_lib[d].xy)if(g=ntsSeq$$module$bouw$xmlplay_lib[d].vce,-1!=gStaves$$module$bouw$xmlplay_lib[y].indexOf(g)){var n=e[0];g=e[1];e=e[3];if(!(n<f)&&z<parseFloat(g)+e){iSeq$$module$bouw$xmlplay_lib=d;z=ntsSeq$$module$bouw$xmlplay_lib[d].t;for(isvgPrev$$module$bouw$xmlplay_lib.fill(-1);ntsSeq$$module$bouw$xmlplay_lib[d]&&ntsSeq$$module$bouw$xmlplay_lib[d].t==z;)putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[d]),d+=1;break}}}}}var t="",u="",v=0,p={},r,m,w=1E3,
x=0,y=0;abcElm$$module$bouw$xmlplay_lib=f;abcElm$$module$bouw$xmlplay_lib.style["scroll-behavior"]=d.nosm?"auto":"smooth";document.scrollingElement.style["scroll-behavior"]=d.nosm?"auto":"smooth";rolElm$$module$bouw$xmlplay_lib.style.visibility=d.noDash?"hidden":"visible";if(a){var B=new Abc({imagesize:'width="100%"',img_out:function(a){-1!=a.indexOf("<svg")&&(stfPos$$module$bouw$xmlplay_lib[v]=Object.keys(p),p={},v+=1,r<w&&(w=r),m>x&&(x=m));t+=a},errmsg:function(a,b,d){u+=a+"\n"},read_file:function(a){return""},
anno_start:function(a,b,d,e,c,f,g){if("note"==a||"rest"==a||"grace"==a)e=B.ax(e).toFixed(2),c=B.ay(c).toFixed(2),g=B.ah(g),ntsPos$$module$bouw$xmlplay_lib[b]=[v,e,c,f,g];"bar"==a&&(c=B.ay(c),g=B.ah(g),c=Math.round(c+g),p[c]=1,m=B.ax(e),r=B.ax(0))},get_abcmodel:null});B.tosvg("abc2svg",a);""==u&&(u="no error");e(u.trim());t&&(abcElm$$module$bouw$xmlplay_lib.innerHTML=t,deSvgs$$module$bouw$xmlplay_lib=Array.prototype.slice.call(abcElm$$module$bouw$xmlplay_lib.getElementsByTagName("svg")),deSvgs$$module$bouw$xmlplay_lib.forEach(function(a,
b){var d=a.querySelector(".g");deSvgGs$$module$bouw$xmlplay_lib[b]=d?d:a}),setScale$$module$bouw$xmlplay_lib(),deSvgs$$module$bouw$xmlplay_lib.forEach(function(a){g(a,"click",q)}),c&&(isvgAligned$$module$bouw$xmlplay_lib=-1,iSeq$$module$bouw$xmlplay_lib=0,mkNtsSeq$$module$bouw$xmlplay_lib(d.tomsr)),document.addEventListener("scrollend",eindRol$$module$bouw$xmlplay_lib))}}
function setScale$$module$bouw$xmlplay_lib(){if(0!=deSvgs$$module$bouw$xmlplay_lib.length){var a=deSvgs$$module$bouw$xmlplay_lib.length-1,d=deSvgs$$module$bouw$xmlplay_lib[a];var b=d.getBoundingClientRect().width;try{var c=d.viewBox.baseVal.width}catch(e){c=b}var f=(f=deSvgGs$$module$bouw$xmlplay_lib[a].transform)?f.baseVal:[];a=f.length?f.getItem(0).matrix.a:1;gScale$$module$bouw$xmlplay_lib=c/a/b}}
function mkNtsSeq$$module$bouw$xmlplay_lib(a){var d=0<iSeq$$module$bouw$xmlplay_lib&&ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib]?ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].t:0,b=1,c=0,f=0,e=0,g=0,k=0,h;ntsSeq$$module$bouw$xmlplay_lib=[];barTimes$$module$bouw$xmlplay_lib={};for(h=0;h<allNotes$$module$bouw$xmlplay_lib.length;++h){var l=allNotes$$module$bouw$xmlplay_lib[h];if(l.bt&&0==l.v){if(l.t in barTimes$$module$bouw$xmlplay_lib&&":"==l.bt[0])continue;if(1==
b&&":"==l.bt[0]&&l.t>e){h=f-1;b=2;c+=l.t-e;continue}2==b&&":"==l.bt[0]&&l.t>e&&(b=1);1==b&&":"==l.bt[l.bt.length-1]&&(f=h,e=l.t);g&&(l.tx||"|"!=l.bt)&&(g=0,c-=l.t-k);2==b&&"1"==l.tx&&(g=1,k=l.t)}g||(l.bt?barTimes$$module$bouw$xmlplay_lib[l.t]=l.t+c:ntsSeq$$module$bouw$xmlplay_lib.push({t:l.t+c,xy:metRects$$module$bouw$xmlplay_lib?l.ix:ntsPos$$module$bouw$xmlplay_lib[l.ix],ns:l.ns,vce:l.v,inv:l.inv,tmp:l.tmp}))}b=Object.keys(barTimes$$module$bouw$xmlplay_lib);0==d&&0<a&&(d=barTimes$$module$bouw$xmlplay_lib[b[a-
1]]);for(iSeq$$module$bouw$xmlplay_lib=0;iSeq$$module$bouw$xmlplay_lib<ntsSeq$$module$bouw$xmlplay_lib.length&&(l=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib],!(l.t>=d)||l.inv);++iSeq$$module$bouw$xmlplay_lib);iSeq$$module$bouw$xmlplay_lib==ntsSeq$$module$bouw$xmlplay_lib.length&&--iSeq$$module$bouw$xmlplay_lib;putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib])}
function rolRegel$$module$bouw$xmlplay_lib(a,d){var b=deSvgGs$$module$bouw$xmlplay_lib[d].getBoundingClientRect().top;b+=(stfPos$$module$bouw$xmlplay_lib[d][0]-stfHgt$$module$bouw$xmlplay_lib[0])/gScale$$module$bouw$xmlplay_lib;d=rolElm$$module$bouw$xmlplay_lib.getBoundingClientRect().bottom;b=Math.round(b-d);0!=b&&(a.scrollTop+=b)}
function alignSystem$$module$bouw$xmlplay_lib(a){if(a!=isvgAligned$$module$bouw$xmlplay_lib)if(isvgAligned$$module$bouw$xmlplay_lib=a,abcElm$$module$bouw$xmlplay_lib.clientHeight<abcElm$$module$bouw$xmlplay_lib.scrollHeight){alignActive$$module$bouw$xmlplay_lib=1;var d=abcElm$$module$bouw$xmlplay_lib.getBoundingClientRect();a=rolElm$$module$bouw$xmlplay_lib.getBoundingClientRect().bottom;a=Math.round(d.top-a)+100;if(d=0!=a)d=document.scrollingElement,d=d.clientHeight<d.scrollHeight;d?document.scrollingElement.scrollTop+=
a:eindRol$$module$bouw$xmlplay_lib()}else rolRegel$$module$bouw$xmlplay_lib(document.scrollingElement,a)}function eindRol$$module$bouw$xmlplay_lib(){alignActive$$module$bouw$xmlplay_lib&&(rolRegel$$module$bouw$xmlplay_lib(abcElm$$module$bouw$xmlplay_lib,isvgAligned$$module$bouw$xmlplay_lib),alignActive$$module$bouw$xmlplay_lib=0)}
function putMarkLoc$$module$bouw$xmlplay_lib(a,d=1){var b,c;if(metRects$$module$bouw$xmlplay_lib)putMarkExt$$module$bouw$xmlplay_lib(a);else{var f=rMarks$$module$bouw$xmlplay_lib[a.vce];if(b=a.xy){var e=b[0];var g=b[1];var k=b[2];var h=b[3];b=b[4];a.inv&&(b=h=0);2==d&&(isvgPrev$$module$bouw$xmlplay_lib[a.vce]=-1);e!=isvgPrev$$module$bouw$xmlplay_lib[a.vce]&&((c=f.parentNode)&&c.removeChild(f),c=deSvgGs$$module$bouw$xmlplay_lib[e],c.insertBefore(f,c.firstChild),isvgPrev$$module$bouw$xmlplay_lib[a.vce]=
e,0<d&&!a.inv&&alignSystem$$module$bouw$xmlplay_lib(e));f.setAttribute("x",g);f.setAttribute("y",k);f.setAttribute("width",h);f.setAttribute("height",b)}else f.setAttribute("width",0),f.setAttribute("height",0)}}
function plaatsLoper$$module$bouw$xmlplay_lib(a){for(var d=1,b,c=0;c<ntsSeq$$module$bouw$xmlplay_lib.length;++c){var f=ntsSeq$$module$bouw$xmlplay_lib[c];if(f.t>a){putMarkLoc$$module$bouw$xmlplay_lib(b,2);break}putMarkLoc$$module$bouw$xmlplay_lib(f,!1);f.t==a&&(d&&(iSeq$$module$bouw$xmlplay_lib=c,d=0),putMarkLoc$$module$bouw$xmlplay_lib(f,!1));f.xy&&(b=f)}}
function naarMaat$$module$bouw$xmlplay_lib(a){for(var d=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].ns[0].t,b=iSeq$$module$bouw$xmlplay_lib;b<ntsSeq$$module$bouw$xmlplay_lib.length&&0<=b;b+=a){var c=ntsSeq$$module$bouw$xmlplay_lib[b].ns[0].t;if(c!=d&&(c in barTimes$$module$bouw$xmlplay_lib||0==c)){plaatsLoper$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[b].t);break}}}
function regelOmhoog$$module$bouw$xmlplay_lib(a){var d,b,c,f,e,g=Infinity;for(c=iSeq$$module$bouw$xmlplay_lib;c<ntsSeq$$module$bouw$xmlplay_lib.length&&0<=c;c+=a)if(ntsSeq$$module$bouw$xmlplay_lib[c].xy&&!ntsSeq$$module$bouw$xmlplay_lib[c].inv)if(b){[f,e]=ntsSeq$$module$bouw$xmlplay_lib[c].xy;f==d+a&&Math.abs(b-e)<g&&(g=Math.abs(b-e),iSeq$$module$bouw$xmlplay_lib=c);if(1==a&&f>d+a)break;if(-1==a&&f<d+a)break}else[d,b]=ntsSeq$$module$bouw$xmlplay_lib[c].xy;plaatsLoper$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib].t)}
function markeer$$module$bouw$xmlplay_lib(){if(audioCtx$$module$bouw$xmlplay_lib){var a=1E3*audioCtx$$module$bouw$xmlplay_lib.currentTime,d=gAccTime$$module$bouw$xmlplay_lib-a;a+=d;for(var b=0,c;0==b;){var f=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib];c=156.25/(f.tmp*tmpElm$$module$bouw$xmlplay_lib.value);iSeq$$module$bouw$xmlplay_lib==ntsSeq$$module$bouw$xmlplay_lib.length-1?(iSeq$$module$bouw$xmlplay_lib=-1,b=f.ns[0].dur+1E3):(b=ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib+
1].t,b=(b-f.t)*c);var e="arpeggio"==f.ns[0].orn.naam?f.ns[0].orn.ard*c:0;f.ns.forEach(function(b,d){speel$$module$bouw$xmlplay_syn(a+d*e,b.inst,b.mnum,b.cnt,b.dur,c,f.vce,b.velo,b.orn)});setTimeout(function(a){putMarkLoc$$module$bouw$xmlplay_lib(a)},d,f);iSeq$$module$bouw$xmlplay_lib+=1}gAccTime$$module$bouw$xmlplay_lib+=b;clearTimeout(timer1$$module$bouw$xmlplay_lib);timer1$$module$bouw$xmlplay_lib=setTimeout(markeer$$module$bouw$xmlplay_lib,d+b-50)}else alert(alrtMsg2)}
function start_markeer$$module$bouw$xmlplay_lib(a,d){tmpElm$$module$bouw$xmlplay_lib=document.getElementById("tempo")||{value:1};audioCtx$$module$bouw$xmlplay_lib=a;gAccTime$$module$bouw$xmlplay_lib=1E3*audioCtx$$module$bouw$xmlplay_lib.currentTime;if(d){[a]=d.id.slice(1).split("_").map(a=>parseInt(a));d=0;for(var b=Infinity,c=0;c<ntsSeq$$module$bouw$xmlplay_lib.length;++c){var f=ntsSeq$$module$bouw$xmlplay_lib[c].xy-a;0<=f&&f<b&&(b=f,d=c)}iSeq$$module$bouw$xmlplay_lib=d}markeer$$module$bouw$xmlplay_lib()}
function stop_markeer$$module$bouw$xmlplay_lib(){clearTimeout(timer1$$module$bouw$xmlplay_lib)}function mapPerc$$module$bouw$xmlplay_lib(a){var d,b={},c={};a=a.split("\n");for(d=0;d<a.length;++d){var f=a[d];if(0<=f.indexOf("%%map")){var e=f.match(/%%map *(\S+) *(\S+).*midi=(\d+)/);f=f.match(/%%map *(\S+) /);if(e){f=e[1];var g=e[2];e=e[3];b[f+g]=parseInt(e)}else f&&(f=f[1],c[f]=1)}}return[c,b]}
function perc2map$$module$bouw$xmlplay_lib(a){var d={diamond:1,triangle:1,square:1,normal:1},b='%%beginsvg\n<defs>,<text id="x" x="-3" y="0">&#xe263;</text>,<text id="x-" x="-3" y="0">&#xe263;</text>,<text id="x+" x="-3" y="0">&#xe263;</text>,<text id="normal" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal-" x="-3.7" y="0">&#xe0a3;</text>,<text id="normal+" x="-3.7" y="0">&#xe0a4;</text>,<g id="circle-x"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<g id="circle-x-"><text x="-3" y="0">&#xe263;</text><circle r="4" class="stroke"></circle></g>,<path id="triangle" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle-" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="stroke-width:1.4"></path>,<path id="triangle+" d="m-4 -3.2l4 6.4 4 -6.4z" class="stroke" style="fill:#000"></path>,<path id="square" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square-" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="square+" d="m-3.5 3l0 -6.2 7.2 0 0 6.2z" class="stroke" style="fill:#000"></path>,<path id="diamond" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond-" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="stroke-width:1.4"></path>,<path id="diamond+" d="m0 -3l4.2 3.2 -4.2 3.2 -4.2 -3.2z" class="stroke" style="fill:#000"></path>,</defs>\n%%endsvg'.split(","),c,
f="default",e={"default":[]},g={"default":[]};var k=a.split("\n");for(c=0;c<k.length;++c){var h=k[c];if(0<=h.indexOf("I:percmap")){h=h.split(/\s+/).map(a=>a.trim());if(5>h.length)return a;var l=h[4];l in d&&(l=l+"+,"+l);h="%%map perc"+f+" "+h[1]+" print="+h[2]+" midi="+h[3]+" heads="+l;e[f].push(h)}0<=h.indexOf("%%MIDI")&&g[f].push(h);0<=h.indexOf("V:")&&(l=h.match(/V:\s*(\S+)/))&&(f=l[1],f in e||(e[f]=[],g[f]=[]))}a=Object.keys(e).sort();for(c=0;c<a.length;++c)b=b.concat(e[a[c]]);f="default";for(c=
0;c<k.length;++c)h=k[c],0<=h.indexOf("I:percmap")||0<=h.indexOf("%%MIDI")||(0<=h.indexOf("V:")||0<=h.indexOf("K:")?((l=h.match(/V:\s*(\S+)/))&&(f=l[1]),b.push(h),f in g&&g[f].length&&(b=b.concat(g[f]),delete g[f]),0<=h.indexOf("perc")&&-1==h.indexOf("map=")&&(h+=" map=perc"),0<=h.indexOf("map=perc")&&0<e[f].length&&b.push("%%voicemap perc"+f),0<=h.indexOf("map=off")&&b.push("%%voicemap")):b.push(h));return b.join("\n")}
function schuifLijn$$module$bouw$xmlplay_lib(a){function d(a){rolElm$$module$bouw$xmlplay_lib.style.top=a.clientY-15+"px"}function b(a){a.stopPropagation();rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointermove",d);rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointerup",b);rolElm$$module$bouw$xmlplay_lib.removeEventListener("pointerleave",b);rolElm$$module$bouw$xmlplay_lib.style.cursor="initial";a=isvgAligned$$module$bouw$xmlplay_lib;isvgAligned$$module$bouw$xmlplay_lib=-1;alignSystem$$module$bouw$xmlplay_lib(a)}
rolElm$$module$bouw$xmlplay_lib.style.cursor="row-resize";rolElm$$module$bouw$xmlplay_lib.addEventListener("pointermove",d);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerup",b);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerleave",b)}
function addElms$$module$bouw$xmlplay_lib(){var a=document.createElement("style");a.innerHTML="#rollijn  { position:fixed; height:30px; width:100%; z-index:1; top: 30%; border-bottom: thin dashed black; touch-action: none; }\n#rollijn:hover { cursor: row-resize; background: rgba(0,255,0,0.3); }\n.dlog { display:none; background:lightblue; position:fixed; top: 50%; left: 50%; width:60%; padding:10px; transform: translate(-50%,-50%); z-index:9; overflow: auto; }\n";document.head.appendChild(a);rolElm$$module$bouw$xmlplay_lib=
document.createElement("div");rolElm$$module$bouw$xmlplay_lib.id="rollijn";document.body.appendChild(rolElm$$module$bouw$xmlplay_lib);rolElm$$module$bouw$xmlplay_lib.addEventListener("pointerdown",schuifLijn$$module$bouw$xmlplay_lib);a=document.createElement("div");a.id="comp";a.classList.add("dlog");document.body.appendChild(a)}
var module$bouw$xmlplay_lib={get iSeq(){return iSeq$$module$bouw$xmlplay_lib},get midiUsedArr(){return midiUsedArr$$module$bouw$xmlplay_lib},get ntsSeq(){return ntsSeq$$module$bouw$xmlplay_lib},get stf2name(){return stf2name$$module$bouw$xmlplay_lib},get vce2stf(){return vce2stf$$module$bouw$xmlplay_lib}};module$bouw$xmlplay_lib.addElms=addElms$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.doLayout=doLayout$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.doModel=doModel$$module$bouw$xmlplay_lib;
module$bouw$xmlplay_lib.mapPerc=mapPerc$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiInstr=midiInstr$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiPan=midiPan$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.midiVol=midiVol$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.mkNtsSeq=mkNtsSeq$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.naarMaat=naarMaat$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.perc2map=perc2map$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.putMarkLoc=putMarkLoc$$module$bouw$xmlplay_lib;
module$bouw$xmlplay_lib.regelOmhoog=regelOmhoog$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.setScale=setScale$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.start_markeer=start_markeer$$module$bouw$xmlplay_lib;module$bouw$xmlplay_lib.stop_markeer=stop_markeer$$module$bouw$xmlplay_lib;var xmlplay_VERSION$$module$bouw$xmlplay_emb=188;
(function(){function a(a){console.log(a);a=a.replaceAll("\n","<br>").trim();a.endsWith("<br>")||(a+="<br>");document.getElementById("comp").innerHTML+=a}function d(c,I,H){null!=c.match(/V:\w+\s*tab.*voicemap/s)?delete abc2svg.mhooks.strtab:B&&(abc2svg.mhooks.strtab=B);H&&(0<=c.indexOf("I:percmap")&&(c=perc2map$$module$bouw$xmlplay_lib(c)),0<=c.indexOf("%%map")&&([n,l]=mapPerc$$module$bouw$xmlplay_lib(c)));c.includes("temperamentequal")&&(c='%%beginsvg\n<defs>\n<text id="acc1_3" x="-1">&#xe261; <tspan x="-6" y="-4" style="font-size:14px">&#8593;</tspan></text>\n<text id="acc2_3" x="-1">&#xe262; <tspan x="-5" y="14" style="font-size:14px">&#8595;</tspan></text>\n<text id="acc4_3" x="-1">&#xe262; <tspan x="-5" y="-4" style="font-size:14px">&#8593;</tspan></text>\n<text id="acc-4_3" x="-2">&#xe260; <tspan x="-8.2" y="9" style="font-size:16px">&#8595;</tspan></text>\n<text id="acc-2_3" x="-1">&#xe260; <tspan x="-7.3" y="-1" style="font-size:16px">&#8593;</tspan></text>\n<text id="acc-1_3" x="-1">&#xe261; <tspan x="-2" y="12" style="font-size:14px">&#8595;</tspan></text>\n</defs>\n%%endsvg\n'+c);
v=I;if(H){var z=c,C;for(C in n){var n="%%voicemap "+C;var F=n.replace("%voicemap","_________");z=z.replaceAll(n,F)}doModel$$module$bouw$xmlplay_lib(z,e,120,0,l,a);q=midiVol$$module$bouw$xmlplay_lib;t=midiPan$$module$bouw$xmlplay_lib;u=midiInstr$$module$bouw$xmlplay_lib;h=midiUsedArr$$module$bouw$xmlplay_lib;y=Array(256).fill(1).map((a,b)=>b);setSynVars$$module$bouw$xmlplay_syn(k,e,q,t,u,h,e.withRT,r,m,w,x,y,p,a);laadNoot$$module$bouw$xmlplay_syn(b)}doLayout$$module$bouw$xmlplay_lib(c,e,I,H,v,a,f,
()=>g,b,d)}function b(a){ntsSeq$$module$bouw$xmlplay_lib.length&&((g=a)?start_markeer$$module$bouw$xmlplay_lib(k):stop_markeer$$module$bouw$xmlplay_lib())}function c(){var a,b,d;if(a=document.getElementById("parms"))a.style.display="none";a=a?JSON.parse(a.innerText):{};for(c in a)e[c]=a[c];var c=window.location.href.split("?");if(1<c.length)for(a=c[1].split("&"),b=0;b<a.length;b++)c=a[b],"noRT"==c?e.withRT=0:"nosm"==c?e.nosm=1:"noDash"==c?e.noDash=1:"ios"==c?r=x=w=m=0:"keyt"==c?e.keyt=1:(d=c.match(/sf2=(\w+)/))?
e.sf2url2=d[1]+"/":"rbm"==c?e.rbm=1:"burak"==c?(e.rbm=1,p_url.burak=1):"dynvce"==c&&(e.dynvce=1)}function f(a,b,d){function c(b){a.removeEventListener("mousedown",c);a.removeEventListener("touchend",c);console.log("event listeners removed from "+a.nodeName);k&&"suspended"==k.state&&k.resume().then(function(){console.log("resuming audioContext")})}a.addEventListener("mousedown",c);a.addEventListener("touchend",c);a.addEventListener(b,d)}var e={speed:1,withRT:1,curmsk:0,sf2url1:"./",sf2url2:"",instTab:{},
midijsUrl1:"./",midijsUrl2:"https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/",instList:{},transMap:{},burak:0,nosm:0,noDash:0,arpmaxdur:36,dynvce:0},g=0,k=null,h=[],l={},q=[],t=[],u=[],v=null,p=null,r=1,m=1,w=1,x=1,y,B;document.addEventListener("DOMContentLoaded",async function(){addElms$$module$bouw$xmlplay_lib();c();var a=[...(await (await fetch(window.location.href)).text()).matchAll(/class[^>]*?abc.*?>(.*?)<\/div/sg)],f=Array.prototype.slice.call(document.getElementsByClassName("abc"));
f.forEach(function(c,e){var f=a[e][1];f=f.replace("\x3c!--","").replace("--\x3e","").trim();f="%%fullsvg _"+e+"\n"+f;d(f,c,0);c.setAttribute("tabindex","0");c.addEventListener("keydown",a=>{var e=f,h=a.key;if(a.altKey||a.ctrlKey||a.shiftKey||"Tab"==h||"Escape"==h)b(0);else switch(a.preventDefault(),h){case "ArrowLeft":case "Left":naarMaat$$module$bouw$xmlplay_lib(-1);break;case "ArrowRight":case "Right":naarMaat$$module$bouw$xmlplay_lib(1);break;case "ArrowUp":case "Up":regelOmhoog$$module$bouw$xmlplay_lib(-1);
break;case "ArrowDown":case "Down":regelOmhoog$$module$bouw$xmlplay_lib(1);break;case "m":$("#mbar").click();break;case "t":p.style.display="none"==p.style.display?"block":"none";break;case " ":c==v?b(!g):(b(0),d(e,c,1))}})});f[0].focus();v=null;document.body.addEventListener("pointerup",function(){g&&b(0)},!1);B=abc2svg.mhooks.strtab;window.addEventListener("resize",function(){setScale$$module$bouw$xmlplay_lib();ntsSeq$$module$bouw$xmlplay_lib.length&&putMarkLoc$$module$bouw$xmlplay_lib(ntsSeq$$module$bouw$xmlplay_lib[iSeq$$module$bouw$xmlplay_lib],
2)});p=document.getElementById("comp");f=window.AudioContext||window.webkitAudioContext;k=void 0!=f?new f:null;f=["Your browser does not support:"];var h=0;k?(k.createStereoPanner||(r=0),k.createOscillator||(m=0),k.createBiquadFilter||(w=0),k.createConstantSource||(x=0),r||f.push("* the StereoPanner element"),e.withRT&&!m&&(f.push("* the Oscillator element"),h=1),e.withRT&&!w&&(f.push("* the BiquadFilter element"),h=1),e.withRT&&!x&&(f.push("* the ConstantSource element"),h=1),h&&(f.push("You are probably on iOS, which does not support the Web Audio API."),
f.push("Real time synthesis is switched off, falling back to MIDIjs"),e.withRT=0)):f.push("* the Web Audio API -> no sound");1<f.length&&alert(f.join("\n"))})})();var module$bouw$xmlplay_emb={};
